-- run status: script error: Script:3375: attempt to perform arithmetic (mul) on table and number
--   /tmp/luau-recover-env-utf2ft_1/harness.luau:16531
--   Script:3375
--   /tmp/luau-recover-env-utf2ft_1/harness.luau:16536
--   
-- 2 statements recorded in 0.69s
-- non-standard globals touched: al, c2, bC

--@1 
local HttpService = game:GetService("HttpService")
--@1 
HttpService:JSONDecode("{\"m\":null,\"t\":\"buffer\",\"zbase64\":\"KLUv/SAdvQAA0sEEjhIREAABAAAAA4De+fFCMrSLMAA=\"}")
