"use client";

import { useCallback, useRef, useState } from "react";
import type { JobStats } from "@/db/schema";
import { StatsPanel } from "./StatsPanel";

type Result = { id: string | null; output: string; stats: JobStats; inputSize: number; outputSize: number };

const SAMPLE_URL = "https://raw.githubusercontent.com/joustingmatch/Ouroboros/refs/heads/main/games/stealanegg.lua";

export function DeobfTool() {
  const [mode, setMode] = useState<"paste" | "url" | "file">("paste");
  const [code, setCode] = useState("");
  const [url, setUrl] = useState(SAMPLE_URL);
  const [file, setFile] = useState<File | null>(null);
  const [rename, setRename] = useState(true);
  const [unflatten, setUnflatten] = useState(true);
  const [removeDeadCode, setRemoveDeadCode] = useState(true);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [result, setResult] = useState<Result | null>(null);
  const [copied, setCopied] = useState(false);
  const dropRef = useRef<HTMLDivElement>(null);

  const run = useCallback(async () => {
    setBusy(true);
    setError(null);
    setResult(null);
    try {
      let res: Response;
      const options = { rename, unflatten, removeDeadCode };
      if (mode === "file") {
        if (!file) throw new Error("Choose a file first");
        const fd = new FormData();
        fd.append("file", file);
        res = await fetch("/api/deobfuscate", { method: "POST", body: fd });
      } else if (mode === "url") {
        res = await fetch("/api/deobfuscate", {
          method: "POST",
          headers: { "content-type": "application/json" },
          body: JSON.stringify({ url, options }),
        });
      } else {
        res = await fetch("/api/deobfuscate", {
          method: "POST",
          headers: { "content-type": "application/json" },
          body: JSON.stringify({ code, title: "pasted.lua", options }),
        });
      }
      const data = (await res.json()) as Result & { error?: string };
      if (!res.ok) throw new Error(data.error ?? `Request failed (${res.status})`);
      setResult(data);
    } catch (e) {
      setError(e instanceof Error ? e.message : "Unknown error");
    } finally {
      setBusy(false);
    }
  }, [mode, code, url, file, rename, unflatten, removeDeadCode]);

  const onDrop = (e: React.DragEvent) => {
    e.preventDefault();
    const f = e.dataTransfer.files?.[0];
    if (f) {
      setFile(f);
      setMode("file");
    }
  };

  const copy = async () => {
    if (!result) return;
    await navigator.clipboard.writeText(result.output);
    setCopied(true);
    setTimeout(() => setCopied(false), 1500);
  };

  const download = () => {
    if (!result) return;
    const blob = new Blob([result.output], { type: "text/plain" });
    const a = document.createElement("a");
    a.href = URL.createObjectURL(blob);
    a.download = "deobfuscated.lua";
    a.click();
    URL.revokeObjectURL(a.href);
  };

  const tab = (m: typeof mode, label: string) => (
    <button
      type="button"
      onClick={() => setMode(m)}
      className={`rounded-md px-3 py-1.5 text-sm transition ${mode === m ? "bg-violet-600 text-white" : "text-zinc-400 hover:bg-zinc-800 hover:text-zinc-100"}`}
    >
      {label}
    </button>
  );

  return (
    <div className="space-y-6">
      <div ref={dropRef} onDragOver={(e) => e.preventDefault()} onDrop={onDrop} className="rounded-2xl border border-zinc-800 bg-zinc-900/50 p-4 shadow-xl shadow-black/30 sm:p-6">
        <div className="mb-4 flex flex-wrap items-center justify-between gap-3">
          <div className="flex gap-1 rounded-lg bg-zinc-900 p-1">
            {tab("paste", "Paste")}
            {tab("url", "URL")}
            {tab("file", "Upload")}
          </div>
          <div className="flex flex-wrap items-center gap-4 text-sm text-zinc-400">
            <label className="flex items-center gap-2">
              <input type="checkbox" checked={unflatten} onChange={(e) => setUnflatten(e.target.checked)} className="accent-violet-500" />
              Unflatten control flow
            </label>
            <label className="flex items-center gap-2">
              <input type="checkbox" checked={rename} onChange={(e) => setRename(e.target.checked)} className="accent-violet-500" />
              Rename identifiers
            </label>
            <label className="flex items-center gap-2">
              <input type="checkbox" checked={removeDeadCode} onChange={(e) => setRemoveDeadCode(e.target.checked)} className="accent-violet-500" />
              Remove dead locals
            </label>
          </div>
        </div>

        {mode === "paste" && (
          <textarea
            value={code}
            onChange={(e) => setCode(e.target.value)}
            spellCheck={false}
            placeholder={'-- generated by luast v1.0.1 https://luast.clv.cloud\nlocal adY = {}; local adv; ...'}
            className="scrollbar-thin h-64 w-full resize-y rounded-lg border border-zinc-800 bg-zinc-950 p-3 text-xs text-zinc-200 outline-none focus:border-violet-500"
          />
        )}
        {mode === "url" && (
          <div className="space-y-2">
            <input
              value={url}
              onChange={(e) => setUrl(e.target.value)}
              placeholder="https://raw.githubusercontent.com/user/repo/main/script.lua"
              className="w-full rounded-lg border border-zinc-800 bg-zinc-950 p-3 text-sm text-zinc-200 outline-none focus:border-violet-500"
            />
            <p className="text-xs text-zinc-500">GitHub blob links are converted to raw automatically. Max 4 MB.</p>
          </div>
        )}
        {mode === "file" && (
          <label className="flex h-40 cursor-pointer flex-col items-center justify-center rounded-lg border border-dashed border-zinc-700 bg-zinc-950 text-sm text-zinc-400 hover:border-violet-500">
            <input type="file" accept=".lua,.luau,.txt" className="hidden" onChange={(e) => setFile(e.target.files?.[0] ?? null)} />
            {file ? (
              <span className="text-zinc-200">
                {file.name} <span className="text-zinc-500">({(file.size / 1024).toFixed(1)} KB)</span>
              </span>
            ) : (
              <span>Drop a .lua file here or click to choose</span>
            )}
          </label>
        )}

        <div className="mt-4 flex flex-wrap items-center gap-3">
          <button
            type="button"
            onClick={run}
            disabled={busy}
            className="rounded-lg bg-gradient-to-r from-violet-600 to-fuchsia-600 px-5 py-2 text-sm font-semibold text-white shadow-lg shadow-violet-600/30 transition hover:brightness-110 disabled:cursor-not-allowed disabled:opacity-50"
          >
            {busy ? "Analysing…" : "Deobfuscate"}
          </button>
          {mode === "paste" && (
            <button type="button" onClick={() => setCode("")} className="text-sm text-zinc-400 hover:text-zinc-100">
              Clear
            </button>
          )}
          {error && <span className="text-sm text-red-400">{error}</span>}
        </div>
      </div>

      {result && (
        <div className="space-y-4">
          <StatsPanel stats={result.stats} inputSize={result.inputSize} outputSize={result.outputSize} />
          <div className="rounded-2xl border border-zinc-800 bg-zinc-900/50">
            <div className="flex flex-wrap items-center justify-between gap-2 border-b border-zinc-800 px-4 py-2">
              <div className="text-sm font-medium text-zinc-300">Deobfuscated source</div>
              <div className="flex items-center gap-2 text-sm">
                {result.id && (
                  <a href={`/jobs/${result.id}`} className="rounded-md px-3 py-1 text-zinc-300 hover:bg-zinc-800">
                    Side-by-side view
                  </a>
                )}
                <button type="button" onClick={copy} className="rounded-md px-3 py-1 text-zinc-300 hover:bg-zinc-800">
                  {copied ? "Copied!" : "Copy"}
                </button>
                <button type="button" onClick={download} className="rounded-md bg-zinc-800 px-3 py-1 text-zinc-100 hover:bg-zinc-700">
                  Download .lua
                </button>
              </div>
            </div>
            <pre className="scrollbar-thin max-h-[70vh] overflow-auto p-4 text-xs leading-relaxed text-zinc-200">{result.output.length > 400_000 ? result.output.slice(0, 400_000) + "\n\n-- [truncated preview: download for full output]" : result.output}</pre>
          </div>
        </div>
      )}
    </div>
  );
}
