import Link from "next/link";

const PASSES: { name: string; file: string; what: string; sample: string }[] = [
  {
    name: "1. Detection & lexing",
    file: "lexer.ts · index.ts",
    what: "Detects watermarks (luast, luraph, moonsec, …) and structural signals. A lossless Luau tokenizer handles trailing-dot numbers (`3198.`), hex/binary, long strings, backtick strings and compound operators.",
    sample: "-- generated by luast v1.0.1  →  obfuscator=luast, version=1.0.1",
  },
  {
    name: "2. Structural tree",
    file: "tree.ts",
    what: "Groups tokens into if/while/for/do/repeat/function blocks and Luau `if … then … else` expressions without requiring a full grammar, so unknown syntax passes through untouched.",
    sample: "S = if cond then 5 else 17  →  exprif{cond, 5, 17}",
  },
  {
    name: "3. Constant pool",
    file: "passes/constants.ts",
    what: "Finds the literal pool (`adv = { … }`), tracks aliases (`local afN = adv`), simulates the multi-assignment shuffles that permute the pool at runtime, inlines literals at every `adv[n]` read and hoists closure entries into named functions.",
    sample: "FN[afN[898]] = afN[2005]  →  FN.runAutoSteal = fn_2005",
  },
  {
    name: "4. Literal folding & indexing",
    file: "passes/simple.ts",
    what: "Precedence-aware folding of `2 + 3`, `\"a\" .. \"b\"`, `not true`, `(5)`; rewrites `t[\"key\"]` to `t.key`; decodes `\\ddd`/`\\xHH` string escapes.",
    sample: "adv[1476] + adv[1846]  →  0 + 1  →  1",
  },
  {
    name: "5. Control-flow unflattening",
    file: "passes/unflatten.ts",
    what: "Recognises `S = init; while true do S = K - S; if S < … ` dispatchers, resolves every leaf through interval analysis, builds the state graph, decodes arithmetic-encoded branches, then re-structures it with post-dominator joins into if/else and while loops with break/continue.",
    sample: "783-state main dispatcher  →  nested if/while blocks",
  },
  {
    name: "6. Re-sugaring & cleanup",
    file: "passes/simple.ts",
    what: "`X = A; if X then X = B end` → `X = A and B`; `else if` → `elseif`; `not (not X)` → `X`; removes never-read `local x = nil` declarations and pure-access temporaries.",
    sample: "v = a >= 300; if v then v = b >= 60 end  →  v = a >= 300 and b >= 60",
  },
  {
    name: "7. Identifier reconstruction",
    file: "passes/rename.ts",
    what: "Obfuscated 2–3 character locals are renamed using semantic hints: `game:GetService(\"Players\")` → Players, `Instance.new(\"Frame\")` → frame, `require(path.Module)` → Module; everything else becomes `var_N`.",
    sample: "local Fp = game:GetService(\"UserInputService\")  →  local UserInputService = …",
  },
];

export default function DocsPage() {
  return (
    <main className="mx-auto max-w-4xl px-4 py-10 sm:px-6">
      <h1 className="text-2xl font-bold">Engine documentation</h1>
      <p className="mt-2 text-zinc-400">
        The engine is a deterministic, side-effect-free static analyser written in TypeScript (<code>src/lib/deobf</code>). It never executes the
        target script. Each pass is independent and reports what it changed, which is surfaced in the job report.
      </p>

      <div className="mt-8 space-y-4">
        {PASSES.map((p) => (
          <section key={p.name} className="rounded-xl border border-zinc-800 bg-zinc-900/40 p-5">
            <div className="flex flex-wrap items-baseline justify-between gap-2">
              <h2 className="font-semibold">{p.name}</h2>
              <span className="font-mono text-xs text-zinc-500">{p.file}</span>
            </div>
            <p className="mt-2 text-sm text-zinc-400">{p.what}</p>
            <pre className="mt-3 overflow-x-auto rounded-md bg-zinc-950 p-3 text-xs text-violet-200">{p.sample}</pre>
          </section>
        ))}
      </div>

      <section className="mt-10 rounded-xl border border-zinc-800 bg-zinc-900/40 p-5">
        <h2 className="font-semibold">REST API</h2>
        <pre className="mt-3 overflow-x-auto rounded-md bg-zinc-950 p-3 text-xs text-zinc-300">{`POST /api/deobfuscate
Content-Type: application/json
{ "url": "https://raw.githubusercontent.com/…/script.lua" }
{ "code": "-- generated by luast …", "title": "x.lua", "options": { "rename": true, "unflatten": true } }
-- or multipart/form-data with a "file" field

→ { "id": "…", "output": "…", "stats": { … }, "inputSize": 545104, "outputSize": 416167 }

GET /api/jobs                  recent jobs
GET /api/jobs/:id              job JSON
GET /api/jobs/:id?format=raw   plain-text output  (?format=download for attachment)`}</pre>
      </section>

      <section className="mt-6 rounded-xl border border-amber-500/20 bg-amber-500/5 p-5 text-sm text-amber-100/90">
        <h2 className="font-semibold text-amber-200">What “1:1” realistically means</h2>
        <ul className="mt-2 list-disc space-y-1 pl-5">
          <li>Semantics and structure (functions, branches, loops, calls, strings, numbers) are recovered.</li>
          <li>Original identifier names and comments are not present in the obfuscated file — no tool can restore them; they are reconstructed heuristically.</li>
          <li>Opaque predicates that depend on runtime state (e.g. `vector.dot` register tricks) are left in place as conditions; they are semantically inert but visible.</li>
          <li>Unknown obfuscator layers fall back gracefully: unmatched code passes through untouched, and the report lists warnings.</li>
        </ul>
        <p className="mt-3">
          Try it on the bundled sample from the <Link href="/" className="underline">home page</Link> (URL tab).
        </p>
      </section>
    </main>
  );
}
