local d5;
local ck;
local cy;
local cn;
local cq;
local cB;
local ct;
local ci;
local cw;
local cl;
local co;
local cz;
local cr;
local cj;
local cu;
local cm;
local cx;
local cp;
local cA;
local cs;
local ch;
local cv;
d5 = {
    1.01,
    "Name",
        function()
        local dl, dn, dp, dq = nil, nil, nil, nil;
        local dm = nil;
        dm = 1;
        while true do
            dm = 11854-dm;
            do
                if dm < 11854 then
                    if dm < 10497. then
                        break;
                    elseif dm < 11800 then
                        break;
                    elseif dm < 11853. then
                        break;
                    elseif dm == 11853. then
                        dp = false;
                        for ai in co do
                            dq = ai;
                            local dr = dq;
                            local dn = nil;
                            local d6 = d5;
                            dn = 0.0;
                            while true do
                                if dn < 4 then
                                    if dn < 2 then
                                        if dn < 1 then
                                            dl = cl["Unloaded"];
                                            dn = if dl then 3.0 else 6.0;
                                        else
                                            dn = 5;
                                        end
                                    elseif dn < 3. then
                                        dl = cq[dr];
                                        dn = if dl then 8 else 1;
                                    else
                                        dn = if dl then 4 else 2;
                                    end
                                elseif dn < 6. then
                                    if dn < 5 then
                                        dn = "hwid";
                                    else
                                        break;
                                    end
                                elseif dn < 7 then
                                    dl = not cx["AutoBuy"]["Value"];
                                    dn = 3.0;
                                elseif dn < 8 then
                                    dp = true;
                                    dn = 5;
                                else
                                    d6[94](dl);
                                    local d7 = d6[15.]["wait"];
                                    d6[187](0.15);
                                    dn = 1;
                                end
                            end
                            if dp then
                                break;
                            end
                        end
                        dm = 0.;
                    else
                        dm = 11800;
                        continue;
                    end
                else
                    break;
                end
            end
        end
    end,
    7,
    "%d+%.?%d*",
    "Collect Cash",
    "Footer",
    "Buyables",
    "ybk",
    "rylapb",
    11160903.,
    "vdbrpwaw",
    81.,
    "LocalPlayer",
    task,
    4704723.,
    print,
    8,
    "Size",
    686,
    71621019.,
    "Text",
    "zvbpsyda",
    "Chicken Farm",
    "NotifySide",
    460,
    3820,
    6.,
    "cfpa",
    "new",
    "Deposit Eggs",
        function()
        d5[94](function()
    cm["InvokeServer"]("Merge Chickens");
end);
    end,
        function()
        cm["InvokeServer"]("Claim Group Reward");
    end,
    0.7,
    62,
    "azvx",
    "ToggleKeybind",
    "settings",
    "wrench",
    "FireServer",
    "uhdumsdzwfm",
        function()
        local c_, c1, c2, c3, c5 = nil, nil, nil, nil, nil;
        local c0 = nil;
        c0 = 1;
        while true do
            c0 = 11818-c0;
            do
                if c0 < 11816 then
                    if c0 < 10483 then
                        break;
                    elseif c0 < 11815 then
                        break;
                    elseif c0 == 11815 then
                        c2 = false;
                        for C, D in c_:GetChildren() do
                            c3 = C;
                            c5 = D;
                            local c4 = c3;
                            local c6 = c5;
                            local c1 = nil;
                            local d8 = d5;
                            c1 = 3.0;
                            while true do
                                if c1 < 3. then
                                    if c1 < 1 then
                                        c1 = if c_ then 2 else 1;
                                    elseif c1 < 2 then
                                        cm["FireServer"]("Collect Egg", c6["Name"]);
                                        c1 = 6.0;
                                    else
                                        c1 = 4;
                                    end
                                elseif c1 < 5 then
                                    if c1 < 4 then
                                        c_ = cl["Unloaded"];
                                        c1 = if c_ then 0.0 else 5;
                                    else
                                        c2 = true;
                                        c1 = 6.0;
                                    end
                                elseif c1 < 6. then
                                    c_ = not cx["AutoCollectEggs"]["Value"];
                                    c1 = 0.0;
                                else
                                    break;
                                end
                            end
                            if c2 then
                                break;
                            end
                        end
                        c0 = 0.;
                    else
                        c0 = 10483;
                        continue;
                    end
                elseif c0 < 13525 then
                    if c0 < 11817. then
                        if c0 == 11816 then
                            return;
                        else
                            c0 = 4273;
                            continue;
                        end
                    elseif c0 < 11818 then
                        if c0 == 11817. then
                            c_ = d5[227]:FindFirstChild("Eggs");
                            c0 = if not c_ then 2 else 3.;
                        else
                            c0 = 5988.;
                            continue;
                        end
                    else
                        break;
                    end
                else
                    break;
                end
            end
        end
    end,
    "xdkpgxhgwy",
    "Join Discord for Keyless Scripts",
    16687805,
        function()
        local c7, c9, da, db, dd = nil, nil, nil, nil, nil;
        local c8 = nil;
        c8 = 0.;
        while true do
            c8 = 3777.-c8;
            do
                if c8 < 3777. then
                    if c8 < 3775 then
                        if c8 < 3774. then
                            break;
                        else
                            da = false;
                            for K, L in c7:GetChildren() do
                                db = K;
                                dd = L;
                                local dc = db;
                                local de = dd;
                                local c9 = nil;
                                c9 = 5;
                                while true do
                                    if c9 < 3. then
                                        if c9 < 1 then
                                            de:Destroy();
                                            c9 = 1;
                                        elseif c9 < 2 then
                                            break;
                                        else
                                            da = true;
                                            c9 = 1;
                                        end
                                    elseif c9 < 5 then
                                        if c9 < 4 then
                                            c9 = if c7 then 4 else 0.0;
                                        else
                                            c9 = 2;
                                        end
                                    elseif c9 < 6. then
                                        c7 = cl["Unloaded"];
                                        c9 = if c7 then 3.0 else 6.0;
                                    else
                                        c7 = not cx["RemoveEggModels"]["Value"];
                                        c9 = 3.0;
                                    end
                                end
                                if da then
                                    break;
                                end
                            end
                            c8 = 1;
                        end
                    elseif c8 < 3776 then
                        return;
                    else
                        break;
                    end
                elseif c8 < 10404. then
                    if c8 < 8555 then
                        if c8 == 3777. then
                            c7 = d5[227]:FindFirstChild("Eggs");
                            c8 = if not c7 then 2 else 3.;
                        else
                            c8 = 3776;
                            continue;
                        end
                    else
                        break;
                    end
                else
                    break;
                end
            end
        end
    end,
    "MenuKeybind",
    newproxy,
    2556.,
    "sqarxaqexa",
    "Minimum Egg Multiplier",
    16043268.,
        function()
        local d4 = nil;
        d4 = 4;
        while true do
            d4 = 6491-d4;
            do
                if d4 < 6486. then
                    if d4 < 6484 then
                        if d4 < 6483. then
                            if d4 < 4988 then
                                break;
                            elseif d4 < 6482 then
                                break;
                            elseif d4 == 6482 then
                                d4 = if not cl["Unloaded"] then 7 else 0.;
                            else
                                d4 = 15086;
                                continue;
                            end
                        else
                            d4 = 3.;
                        end
                    elseif d4 < 6485 then
                        if d4 == 6484 then
                            d4 = if cx["AutoUpgrade"]["Value"] then 6. else 2;
                        else
                            d4 = 15086;
                            continue;
                        end
                    elseif d4 == 6485 then
                        ci();
                        d4 = 2;
                    else
                        d4 = 6484;
                        continue;
                    end
                elseif d4 < 6490 then
                    if d4 < 6489. then
                        if d4 < 6487 then
                            if d4 == 6486. then
                                d4 = 1;
                            else
                                d4 = 6488;
                                continue;
                            end
                        elseif d4 < 6488 then
                            if d4 == 6487 then
                                d4 = 3.;
                            else
                                d4 = 15086;
                                continue;
                            end
                        elseif d4 == 6488 then
                            d4 = if true then 9. else 5;
                        else
                            d4 = 6489.;
                            continue;
                        end
                    elseif d4 == 6489. then
                        local d9 = d5[15.]["wait"];
                        d5[187](0.5);
                        d4 = 8;
                    else
                        d4 = 4988;
                        continue;
                    end
                elseif d4 < 6608 then
                    if d4 < 6491 then
                        break;
                    elseif d4 == 6491 then
                        d4 = 5;
                    else
                        break;
                    end
                else
                    break;
                end
            end
        end
    end,
    1512.,
    97,
    16,
    3184968162.,
    "Farm",
    "25",
    "AutoBuy",
    "Menu",
    "jsfujxkbfze",
    13,
        function()
        local dy = nil;
        dy = 3.;
        while true do
            dy = 9941-dy;
            do
                if dy < 9938 then
                    if dy < 9935 then
                        break;
                    elseif dy < 9936. then
                        dy = 2;
                    elseif dy < 9937 then
                        break;
                    else
                        dy = if toclipboard then 1 else 6.;
                    end
                elseif dy < 9941 then
                    if dy < 9939. then
                        if dy == 9938 then
                            dy = if setclipboard then 0. else 4;
                        else
                            dy = 9939.;
                            continue;
                        end
                    elseif dy < 9940 then
                        if dy == 9939. then
                            cl:Notify("Copied Discord invite to clipboard");
                            dy = 5;
                        else
                            dy = 14108;
                            continue;
                        end
                    else
                        toclipboard(cj);
                        dy = 6.;
                    end
                elseif dy < 13883 then
                    if dy == 9941 then
                        setclipboard(cj);
                        dy = 2;
                    else
                        break;
                    end
                else
                    break;
                end
            end
        end
    end,
    3.,
    "haeqbbuoq",
    "Remove Egg Models",
    "jobId",
    1095.,
    4083.,
    2517909275,
    "MinimumEggMultiplier",
    "Copied Discord invite to clipboard",
    1393569622,
    "Right",
    "1",
    60807799,
    "qtansbp",
    "wzsafot",
    "Ouroboros Hub",
    "AutoDeposit",
    "Chicken Farm unloaded",
    "Auto Merge",
    Vector2.new,
    "pypgusigdkzn",
    0.3,
    "Mint",
    "bbsaoox",
    "AutoUpgrade",
    7087336,
    19,
    "plspt",
    "InvokeServer",
    pcall,
        function(a2)
        local dS, dT, dU = nil, nil, nil;
        local dR = nil;
        dR = 5;
        while true do
            dR = 5342-dR;
            do
                if dR < 5340. then
                    if dR < 5336 then
                        if dR < 5334. then
                            break;
                        elseif dR < 5335 then
                            if dR == 5334. then
                                ck:Disconnect();
                                ck = nil;
                                dR = 6.;
                            else
                                dR = 15272;
                                continue;
                            end
                        elseif dR == 5335 then
                            dR = if ck then 8 else 6.;
                        else
                            dR = 5340.;
                            continue;
                        end
                    elseif dR < 5338 then
                        if dR < 5337. then
                            if dR == 5336 then
                                dR = 0.;
                            else
                                dR = 3558.;
                                continue;
                            end
                        else
                            dU = if a2 then 1 else 0.0;
                            dS = 4006*dU+45.0*(1-dU);
                            dT = 4083.0*dU+3231.0*(1-dU);
                            dR = if (dS*460+dT*"qiob"+dS*dT)%16777213 == 16043268.0 then 1 else 7;
                        end
                    elseif dR < 5339 then
                        break;
                    else
                        ck = cs["Idled"]:Connect(function()
    cw:CaptureController();
    cw:ClickButton2(d5[179]["new"]());
end);
                        dR = 2;
                    end
                elseif dR < 7731. then
                    if dR < 5341 then
                        dR = 0.;
                    elseif dR < 5342 then
                        if dR == 5341 then
                            dU = if not ck then 1 else 0.0;
                            dS = 3891925009*dU+2811.0*(1-dU);
                            dT = 985*dU+1375*(1-dU);
                            dR = if (dS*2556.0+dT*3820+dS*dT)%16777213 == 13542942.0 then 3. else 2;
                        else
                            dR = 16022;
                            continue;
                        end
                    elseif dR == 5342 then
                        dR = 4;
                    else
                        dR = 5335;
                        continue;
                    end
                else
                    break;
                end
            end
        end
    end,
    "Buy Chickens Amount",
    "Anti-AFK",
    985,
    20,
    "yvo",
    "Max",
    3891925009,
    10,
    "AutoCollectEggs",
    16777213,
    1109999133.,
    workspace,
    "ontmrmvgm",
    2,
    "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_",
    "lyjhk",
    3900.,
    "Toggles",
    "AutoMerge",
    "qiob",
    "eloycz",
    71,
    "(.)",
    3412,
    2811.,
        function()
        cm["InvokeServer"]("Upgrade Buy Tier Level");
    end,
    "Eggs",
    1457,
    "RightShift",
    "Unloaded",
    "Rounding",
    113,
    "Join Discord to Make Money",
    "yzopd",
    "Default",
        function()
        cl:Unload();
    end,
    "Idled",
    640,
    "Func",
    "rkamslf",
    18657887261,
    "VirtualUser",
    "BuyChickensAmount",
    0.,
        function()
        cm["InvokeServer"]("Merge Chickens");
    end,
    "ReplicatedStorage",
    17,
    "NoUI",
    "hwid",
    15.,
    "RemoveEggModels",
    task.spawn,
        function(aG)
        local aH = aG:AddLeftGroupbox("Discord");
        aH:AddButton({ ["Text"] = "Multi", ["Func"] = cv });
        aH:AddButton({ ["Text"] = "Join Discord for Keyless Scripts", ["Func"] = cv });
    end,
    "Callback",
    "Icon",
    "Upgrade Process Level",
    "addons/ThemeManager.lua",
    88,
    "yztacspns",
        function()
        local d3 = nil;
        d3 = 1;
        while true do
            d3 = 8201-d3;
            do
                if d3 < 8198 then
                    if d3 < 8194 then
                        if d3 < 8193. then
                            if d3 < 5892. then
                                break;
                            elseif d3 < 7909 then
                                break;
                            elseif d3 < 8192 then
                                break;
                            else
                                local ea = d5[15.]["wait"];
                                d5[187](0.5);
                                d3 = 6.;
                            end
                        elseif d3 == 8193. then
                            cr();
                            d3 = 9.;
                        else
                            d3 = 8199.;
                            continue;
                        end
                    elseif d3 < 8196. then
                        if d3 < 8195 then
                            break;
                        elseif d3 == 8195 then
                            d3 = 3.;
                        else
                            d3 = 8192;
                            continue;
                        end
                    elseif d3 < 8197 then
                        if d3 == 8196. then
                            d3 = 7;
                        else
                            d3 = 14876;
                            continue;
                        end
                    else
                        d3 = if cx["AutoMerge"]["Value"] then 8 else 9.;
                    end
                elseif d3 < 8200 then
                    if d3 < 8199. then
                        d3 = if true then 2 else 5;
                    else
                        d3 = if not cl["Unloaded"] then 4 else 0.;
                    end
                elseif d3 < 9428 then
                    if d3 < 8201 then
                        if d3 == 8200 then
                            d3 = 3.;
                        else
                            d3 = 8199.;
                            continue;
                        end
                    elseif d3 == 8201 then
                        d3 = 5;
                    else
                        d3 = 8192;
                        continue;
                    end
                else
                    break;
                end
            end
        end
    end,
    game,
    "Network",
    "xpqh",
        function()
        local dV = nil;
        dV = 1;
        while true do
            dV = 12416-dV;
            do
                if dV < 10566. then
                    break;
                elseif dV < 12415 then
                    if dV < 12413 then
                        break;
                    elseif dV < 12414. then
                        ck:Disconnect();
                        ck = nil;
                        dV = 0.;
                    else
                        break;
                    end
                elseif dV < 14254 then
                    if dV < 12416 then
                        dV = if ck then 3. else 0.;
                    elseif dV == 12416 then
                        d5[17]("Chicken Farm unloaded");
                        dV = 2;
                    else
                        dV = 12414.;
                        continue;
                    end
                else
                    break;
                end
            end
        end
    end,
    "Discord",
    "bdjgiu",
    "lmp",
    "spawn",
    CFrame.fromMatrix,
    "wheat",
    0.15,
    "Upgrades",
    45.,
        function(aW)
        local dJ, dL, dM, dN, dP = nil, nil, nil, nil, nil;
        local dK = nil;
        dK = 1;
        while true do
            dK = 922-dK;
            do
                if dK < 1456 then
                    if dK < 922 then
                        if dK == 921. then
                            dJ = {};
                            dM = false;
                            for aY, aZ in aW do
                                dN = aY;
                                dP = aZ;
                                local dO = dN;
                                local dQ = dP;
                                local dL = nil;
                                local eb = d5;
                                dL = 4;
                                while true do
                                    if dL < 2 then
                                        if dL < 1 then
                                            dJ[dO] = true;
                                            dL = 2;
                                        else
                                            dM = true;
                                            dL = 3.0;
                                        end
                                    elseif dL < 3. then
                                        dL = 3.0;
                                    elseif dL < 4 then
                                        break;
                                    else
                                        dL = if dQ then 0.0 else 2;
                                    end
                                end
                                if dM then
                                    break;
                                end
                            end
                            ch = dJ;
                            dK = 0.;
                        else
                            break;
                        end
                    else
                        break;
                    end
                else
                    break;
                end
            end
        end
    end,
    "number",
    "Auto Collect Eggs",
    "Auto Collect works, but collected eggs stay on the conveyor visually. Enable Remove Egg Models to clear them locally.",
    "ilmjh",
        function()
        local d2 = nil;
        d2 = 8;
        while true do
            d2 = 2500-d2;
            do
                if d2 < 2497 then
                    if d2 < 2494 then
                        if d2 < 2492 then
                            if d2 < 1649 then
                                break;
                            elseif d2 < 2491 then
                                break;
                            else
                                d2 = 4;
                            end
                        elseif d2 < 2493. then
                            d2 = 3.;
                        else
                            local ec = d5[15.]["wait"];
                            d5[187](0.5);
                            d2 = 2;
                        end
                    elseif d2 < 2495 then
                        if d2 == 2494 then
                            d2 = if cx["AutoBuy"]["Value"] then 0. else 7;
                        else
                            d2 = 1649;
                            continue;
                        end
                    elseif d2 < 2496. then
                        if d2 == 2495 then
                            d2 = if not cl["Unloaded"] then 6. else 9.;
                        else
                            d2 = 2492;
                            continue;
                        end
                    elseif d2 == 2496. then
                        d2 = 1;
                    else
                        d2 = 13319;
                        continue;
                    end
                elseif d2 < 4124 then
                    if d2 < 2499. then
                        if d2 < 2498 then
                            d2 = if true then 5 else 4;
                        else
                            d2 = 3.;
                        end
                    elseif d2 < 2500 then
                        break;
                    elseif d2 == 2500 then
                        cz();
                        d2 = 7;
                    else
                        d2 = 7607;
                        continue;
                    end
                else
                    break;
                end
            end
        end
    end,
    "Multi",
        function()
        local df, dg, di, dj, dk = nil, nil, nil, nil, nil;
        local dh = nil;
        dh = 11;
        while true do
            dh = 13108-dh;
            do
                if dh < 13096 then
                    if dh < 9219. then
                        break;
                    elseif dh < 11662 then
                        break;
                    elseif dh < 13094 then
                        if dh < 13093 then
                            break;
                        else
                            df = dg;
                            dg = df;
                            dh = if dg then 7 else 5;
                        end
                    elseif dh < 13095. then
                        break;
                    else
                        return;
                    end
                elseif dh < 13103 then
                    if dh < 13099 then
                        if dh < 13097 then
                            df = dg;
                            dg = df;
                            dh = if dg then 2 else 15.;
                        elseif dh < 13098. then
                            df = d5[227]:FindFirstChild("Map");
                            dg = df;
                            dk = if dg then 1 else 0.0;
                            di = 1957*dk+733*(1-dk);
                            dh = 10;
                        else
                            dj = 3900.0*dk+3018.0*(1-dk);
                            dh = 9.;
                        end
                    elseif dh < 13101. then
                        if dh < 13100 then
                            dh = if (di*1457+dj*"NoUI"+di*dj)%16777213 == 686 then 8 else 3.;
                        elseif dh == 13100 then
                            dg = df:FindFirstChild(9.0);
                            dh = 3.;
                        else
                            dh = 9456.;
                            continue;
                        end
                    elseif dh < 13102 then
                        if dh == 13101. then
                            dg = tonumber(df["Text"]:match("%d+%.?%d*"));
                            dh = 5;
                        else
                            dh = 13104.;
                            continue;
                        end
                    elseif dh == 13102 then
                        dg = df < ct["MinimumEggMultiplier"]["Value"];
                        dh = 0.;
                    else
                        dh = 5118.;
                        continue;
                    end
                elseif dh < 13107. then
                    if dh < 13105 then
                        if dh < 13104. then
                            if dh == 13103 then
                                df = dg;
                                dg = not df;
                                dh = if dg then 0. else 6.;
                            else
                                dh = 9219.;
                                continue;
                            end
                        elseif dh == 13104. then
                            dg = df:FindFirstChild("UI");
                            dh = 12.;
                        else
                            dh = 13108;
                            continue;
                        end
                    elseif dh < 13106 then
                        if dh == 13105 then
                            df = dg;
                            dg = df;
                            dh = if dg then 4 else 12.;
                        else
                            dh = 11579;
                            continue;
                        end
                    elseif dh == 13106 then
                        dg = df:FindFirstChild("vdbrpwaw");
                        dh = 15.;
                    else
                        dh = 8980;
                        continue;
                    end
                elseif dh < 14017 then
                    if dh < 13108 then
                        d5[94](function()
    cm["InvokeServer"]("Title");
end);
                        dh = 14;
                    elseif dh == 13108 then
                        dh = if dg then 13 else 1;
                    else
                        break;
                    end
                else
                    break;
                end
            end
        end
    end,
    96.,
        function()
        local d1 = nil;
        d1 = 1;
        while true do
            d1 = 12351.-d1;
            do
                if d1 < 12348. then
                    if d1 < 12346 then
                        if d1 < 12345. then
                            if d1 < 12344 then
                                if d1 < 11438 then
                                    break;
                                elseif d1 < 12342. then
                                    break;
                                elseif d1 < 12343 then
                                    if d1 == 12342. then
                                        d1 = 8;
                                    else
                                        d1 = 12345.;
                                        continue;
                                    end
                                else
                                    break;
                                end
                            else
                                d1 = if not cl["Unloaded"] then 5 else 3.;
                            end
                        else
                            d1 = 4;
                        end
                    elseif d1 < 12347 then
                        d1 = if cx["AutoCollectCash"]["Value"] then 2 else 0.;
                    elseif d1 == 12347 then
                        d1 = if true then 7 else 9.;
                    else
                        d1 = 14478.;
                        continue;
                    end
                elseif d1 < 12350 then
                    if d1 < 12349 then
                        if d1 == 12348. then
                            d1 = 9.;
                        else
                            d1 = 2976.;
                            continue;
                        end
                    else
                        cn();
                        d1 = 0.;
                    end
                elseif d1 < 13845. then
                    if d1 < 12351. then
                        if d1 == 12350 then
                            d1 = 4;
                        else
                            d1 = 12346;
                            continue;
                        end
                    elseif d1 == 12351. then
                        local ed = d5[15.]["wait"];
                        d5[187](0.5);
                        d1 = 6.;
                    else
                        break;
                    end
                else
                    break;
                end
            end
        end
    end,
    Vector2,
    3221344269.,
    29,
    "xpghaetd",
    "AutoCollectCash",
    "Values",
    "cojcwjjk",
    18.,
    task.wait,
    "rzszrjapbh",
    9.,
    "x",
    "ukkhnarkbknn",
    "Settings",
    "Auto Deposit",
    "gljx",
    11,
    "oeep",
    "Library.lua",
    "Min",
    "nmkittx",
        function()
        local dZ, d_, d0 = nil, nil, nil;
        local dY = nil;
        dY = 0.;
        while true do
            dY = 12380-dY;
            do
                if dY < 12376 then
                    if dY < 12374 then
                        if dY < 12373 then
                            if dY < 12372. then
                                if dY < 4408 then
                                    break;
                                elseif dY < 10191. then
                                    break;
                                elseif dY < 12371 then
                                    break;
                                elseif dY == 12371 then
                                    dY = 2;
                                else
                                    dY = 12372.;
                                    continue;
                                end
                            else
                                dY = if true then 7 else 9.;
                            end
                        else
                            d0 = if not cl["Unloaded"] then 1 else 0.0;
                            dZ = 2109.0*d0+97*(1-d0);
                            d_ = 1095.0*d0+"Auto Buy"*(1-d0);
                            dY = if (dZ*3412+d_*1512.0+dZ*d_)%16777213 == 11160903.0 then 6. else 4;
                        end
                    elseif dY < 12375. then
                        if dY == 12374 then
                            dY = if cx["Join Discord to Make Money"]["Value"] then 1 else 5;
                        else
                            dY = 2316.;
                            continue;
                        end
                    elseif dY == 12375. then
                        local ee = d5[15.]["wait"];
                        d5[187](0.5);
                        dY = 3.;
                    else
                        dY = 2597;
                        continue;
                    end
                elseif dY < 12378. then
                    if dY < 12377 then
                        if dY == 12376 then
                            dY = 9.;
                        else
                            dY = 12377;
                            continue;
                        end
                    else
                        dY = 8;
                    end
                elseif dY < 12380 then
                    if dY < 12379 then
                        break;
                    elseif dY == 12379 then
                        cp();
                        dY = 5;
                    else
                        dY = 4408;
                        continue;
                    end
                elseif dY < 13223 then
                    if dY == 12380 then
                        dY = 8;
                    else
                        dY = 13223;
                        continue;
                    end
                else
                    break;
                end
            end
        end
    end,
    136,
    "fromOffset",
    130,
    "shopping-cart",
    "Auto Upgrade",
    1375,
    "AntiAfk",
    5,
    "xywipyj",
    "trending-up",
    4,
    63.,
    "%1%1",
    "Value",
    13542942.,
    "uffvqjdjgly",
    "OuroborosHub",
    "100",
    "kzoqhbjtxs",
    2109.,
    "dym",
    "5",
    12.,
    UDim2,
    "Buy Chickens",
    "Unload",
        function()
        local dW = nil;
        dW = 2;
        while true do
            dW = 2544.-dW;
            do
                if dW < 2541. then
                    if dW < 2538. then
                        if dW < 2536 then
                            if dW == 2535. then
                                dW = 6.;
                            else
                                dW = 2542;
                                continue;
                            end
                        elseif dW < 2537 then
                            break;
                        elseif dW == 2537 then
                            dW = 5;
                        else
                            dW = 6664;
                            continue;
                        end
                    elseif dW < 2540 then
                        if dW < 2539 then
                            dW = 8;
                        elseif dW == 2539 then
                            dW = if true then 4 else 6.;
                        else
                            dW = 10909;
                            continue;
                        end
                    elseif dW == 2540 then
                        dW = if not cl["Unloaded"] then 3. else 9.;
                    else
                        dW = 6664;
                        continue;
                    end
                elseif dW < 2544. then
                    if dW < 2542 then
                        if dW == 2541. then
                            dW = if cx["AutoCollectEggs"]["Value"] then 1 else 0.;
                        else
                            dW = 2536;
                            continue;
                        end
                    elseif dW < 2543 then
                        if dW == 2542 then
                            dW = 5;
                        else
                            dW = 2541.;
                            continue;
                        end
                    else
                        cA();
                        dW = 0.;
                    end
                elseif dW < 6664 then
                    if dW == 2544. then
                        local ef = d5[15.]["wait"];
                        d5[187](0.3);
                        dW = 7;
                    else
                        break;
                    end
                else
                    break;
                end
            end
        end
    end,
        function()
        d5[94](function()
    cm["InvokeServer"]("1");
end);
    end,
    "Title",
    "wait",
        function()
        local dX = nil;
        dX = 6.;
        while true do
            dX = 14630-dX;
            do
                if dX < 14627 then
                    if dX < 14624 then
                        if dX < 14622. then
                            if dX < 5678 then
                                break;
                            elseif dX < 6874 then
                                break;
                            elseif dX < 14621 then
                                break;
                            else
                                dX = 7;
                            end
                        elseif dX < 14623 then
                            dX = 5;
                        elseif dX == 14623 then
                            dX = if true then 0. else 8;
                        else
                            dX = 14621;
                            continue;
                        end
                    elseif dX < 14625. then
                        dX = 7;
                    elseif dX < 14626 then
                        break;
                    elseif dX == 14626 then
                        cu();
                        dX = 1;
                    else
                        dX = 14622.;
                        continue;
                    end
                elseif dX < 14629 then
                    if dX < 14628. then
                        if dX == 14627 then
                            dX = 8;
                        else
                            dX = 14625.;
                            continue;
                        end
                    else
                        dX = if cx["RemoveEggModels"]["Value"] then 4 else 1;
                    end
                elseif dX < 14630 then
                    local eg = d5[15.]["wait"];
                    d5[187](0.3);
                    dX = 9.;
                elseif dX < 14643. then
                    if dX == 14630 then
                        dX = if not cl["Unloaded"] then 2 else 3.;
                    else
                        dX = 14627;
                        continue;
                    end
                else
                    break;
                end
            end
        end
    end,
    3581,
    1777058020,
    "UI",
    "Paper",
    14,
    "Suffix",
    "anl",
    "hmdwy",
    "EggMultiplierPart",
    "https://discord.gg/ehKVq7pf7v",
    "navvixcbs",
        function(aN)
        local dz, dB, dC, dD, dF = nil, nil, nil, nil, nil;
        local dA = nil;
        dA = 1;
        while true do
            dA = 1968.-dA;
            do
                if dA < 5166. then
                    if dA < 1968. then
                        if dA == 1967 then
                            dz = {};
                            dC = false;
                            for aP, aQ in aN do
                                dD = aP;
                                dF = aQ;
                                local dE = dD;
                                local dG = dF;
                                local dB = nil;
                                dB = 4;
                                while true do
                                    if dB < 2 then
                                        if dB < 1 then
                                            dB = 2;
                                        else
                                            dz[dE] = true;
                                            dB = 0.0;
                                        end
                                    elseif dB < 3. then
                                        break;
                                    elseif dB < 4 then
                                        dC = true;
                                        dB = 2;
                                    else
                                        dB = if dG then 1 else 0.0;
                                    end
                                end
                                if dC then
                                    break;
                                end
                            end
                            co = dz;
                            dA = 0.;
                        else
                            break;
                        end
                    else
                        break;
                    end
                else
                    break;
                end
            end
        end
    end,
    6.,
    "Luraph v14.2",
    "vorb",
    "Options",
    2374617845,
    "Claim Group Reward",
    "slboji",
        function()
        cm["InvokeServer"]("Upgrade Process Level");
    end,
    "egg",
    "dfzgrac",
    1,
    4006,
    "ttleqz",
    2762,
        function()
        cm["InvokeServer"]("wrench", cy);
    end,
    "Merge & Upgrade",
    "OuroborosHub/ChickenFarm",
    "ossq",
    "wnv",
    "Upgrade Buy Tier Level",
    733,
    0.5,
    "Main",
    6767,
    Faces.new,
    "khphmkny",
    2283630668,
    "Collect Egg",
    "drizrtnxj",
    79,
    "Players",
    coroutine.yield,
    3018.,
    "Map",
    "Auto Buy",
    "hvyt",
    1957,
    "nmcdrjpwru",
    5,
    "addons/SaveManager.lua",
    "hizlqdd",
    "Auto Collect Cash",
        function(aS)
        local dH = nil;
        local dI = nil;
        dI = 0.;
        while true do
            dI = 11986-dI;
            do
                if dI < 11981 then
                    break;
                elseif dI < 11985. then
                    if dI < 11983 then
                        if dI < 11982. then
                            break;
                        else
                            cy = dH;
                            dI = 5;
                        end
                    elseif dI < 11984 then
                        dH = (tonumber(aS));
                        dI = if dH then 4 else 1;
                    elseif dI == 11984 then
                        aS = cB[aS];
                        dI = 3.;
                    else
                        dI = 281;
                        continue;
                    end
                elseif dI < 14154. then
                    if dI < 11986 then
                        dH = 1;
                        dI = 4;
                    elseif dI == 11986 then
                        dI = if type(aS) == "number" then 2 else 3.;
                    else
                        dI = 2810;
                        continue;
                    end
                else
                    break;
                end
            end
        end
    end,
    900.,
    3231.,
    -1,
    "https://raw.githubusercontent.com/deividcomsono/Obsidian/main/",
    "UI Keybind",
    28,
    "Merge Chickens",
    3431,
};
ch = nil;
ci = nil;
cj = nil;
ck = nil;
cl = nil;
cm = nil;
cn = nil;
co = nil;
cp = nil;
cq = nil;
cr = nil;
cs = nil;
ct = nil;
cu = nil;
cv = nil;
cw = nil;
cx = nil;
cy = nil;
cz = nil;
cA = nil;
cB = nil;
local cC, cD, cE, cF, cG, cH, cI, cJ, cK, cL, cM, cN, cO, cP, cQ, cR, cS, cU, cV, cW, cY = nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil;
local cT = nil;
cT = 173;
while true do
    cT = 11117-cT;
    do
        if cT < 11009 then
            if cT < 10953. then
                if cT < 10924 then
                    if cT < 10910 then
                        if cT < 10903 then
                            if cT < 10900 then
                                if cT < 10898 then
                                    if cT < 10897 then
                                        if cT < 7590. then
                                            break;
                                        elseif cT < 9109 then
                                            break;
                                        elseif cT < 10896. then
                                            break;
                                        elseif cT == 10896. then
                                            cT = if cO <= 2 then 137 else 16;
                                        else
                                            cT = 10960;
                                            continue;
                                        end
                                    else
                                        cF = (cF+6.0)%20;
                                        cT = 142;
                                    end
                                elseif cT < 10899. then
                                    if cT == 10898 then
                                        cP = nil;
                                        local eh = d5;
                                        cP = 4-2;
                                        cP = 4-2;
                                        cP = 6.0-5;
                                        cT = 94;
                                    else
                                        cT = 10981;
                                        continue;
                                    end
                                elseif cT == 10899. then
                                    cT = 58;
                                else
                                    cT = 11005;
                                    continue;
                                end
                            elseif cT < 10902. then
                                if cT < 10901 then
                                    cv = d5[64];
                                    cT = 147.;
                                else
                                    cT = 163;
                                end
                            else
                                cT = 60.;
                            end
                        elseif cT < 10907 then
                            if cT < 10905. then
                                if cT < 10904 then
                                    cT = 149;
                                elseif cT == 10904 then
                                    cT = if cH <= 2 then 127 else 23;
                                else
                                    cT = 11047;
                                    continue;
                                end
                            elseif cT < 10906 then
                                if cT == 10905. then
                                    cT = if cO <= 15.0 then 208 else 156.;
                                else
                                    cT = 11064.;
                                    continue;
                                end
                            elseif cT == 10906 then
                                cP = nil;
                                local eh = d5;
                                cP = 3.0-2;
                                cP = 0.0+1;
                                cP = 2-1;
                                cP = 5-4;
                                cT = 188;
                            else
                                cT = 10908.;
                                continue;
                            end
                        elseif cT < 10909 then
                            if cT < 10908. then
                                local eh = d5;
                                ci = eh[3.];
                                cz = eh[32];
                                cr = function()
    local ds, du, dv, dw = nil, nil, nil, nil;
    local dt = nil;
    dt = 1;
    while true do
        dt = 11832.-dt;
        do
            if dt < 11832. then
                if dt < 10223 then
                    break;
                elseif dt < 11831 then
                    break;
                elseif dt == 11831 then
                    dv = false;
                    for at in ch do
                        dw = at;
                        local dx = dw;
                        local du = nil;
                        local ei = d5;
                        du = 0.0;
                        while true do
                            if du < 3. then
                                if du < 1 then
                                    ds = cl["Unloaded"];
                                    du = if ds then 5 else 6.0;
                                elseif du < 2 then
                                    dv = true;
                                    du = 2;
                                else
                                    break;
                                end
                            elseif du < 5 then
                                if du < 4 then
                                    du = 1;
                                else
                                    ei[94](function()
    cm["InvokeServer"](dx);
end);
                                    local ej = ei[15.]["wait"];
                                    ei[187](0.15);
                                    du = 2;
                                end
                            elseif du < 6. then
                                du = if ds then 3.0 else 4;
                            else
                                ds = not cx["AutoUpgrade"]["Value"];
                                du = 5;
                            end
                        end
                        if dv then
                            break;
                        end
                    end
                    dt = 0.;
                else
                    dt = 11832.;
                    continue;
                end
            else
                break;
            end
        end
    end
end;
                                cT = 18.;
                            else
                                cT = 126.;
                            end
                        elseif cT == 10909 then
                            cT = 69.;
                        else
                            cT = 11091.;
                            continue;
                        end
                    elseif cT < 10917. then
                        if cT < 10914. then
                            if cT < 10912 then
                                if cT < 10911. then
                                    cC = d5[242]:GetService("Players");
                                    cT = 134;
                                elseif cT == 10911. then
                                    local eh = d5;
                                    cO = { "OuroborosHub", "yzopd", 113, "azvx", "khphmkny", "ttleqz", "anl", "rzszrjapbh", "uhdumsdzwfm", "https://discord.gg/ehKVq7pf7v", 96.0, "eloycz" };
                                    local ek = cG;
                                    cP = cO[ek%12.0+1];
                                    cT = if cP:len() >= cP:gsub("(.)", "%1%1", ek%3.0%2+1):len() then 30. else 46;
                                else
                                    cT = 11109.;
                                    continue;
                                end
                            elseif cT < 10913 then
                                cT = if cG*71621019.0+11+1 >= cG*71621019.0+11+1+6.0 then 55 else 22;
                            elseif cT == 10913 then
                                cG = (cG+45.0)%136;
                                cT = 79;
                            else
                                cT = 11050;
                                continue;
                            end
                        elseif cT < 10916 then
                            if cT < 10915 then
                                cG = (cG+130)%136;
                                cT = 167;
                            else
                                cT = 95;
                            end
                        elseif cT == 10916 then
                            cl = loadstring(d5[242]:HttpGet(cE .. "Library.lua"))();
                            cT = 152;
                        else
                            cT = 10980.;
                            continue;
                        end
                    elseif cT < 10921 then
                        if cT < 10919 then
                            if cT < 10918 then
                                if cT == 10917. then
                                    cT = 163;
                                else
                                    cT = 11018;
                                    continue;
                                end
                            else
                                cL = d5[64];
                                cT = 147.;
                            end
                        elseif cT < 10920. then
                            if cT == 10919 then
                                cP = nil;
                                local eh = d5;
                                cP = 16-11;
                                cP = 4-2;
                                cP = 17-10;
                                cP = 0.0+"hwid";
                                cT = 146;
                            else
                                cT = 11091.;
                                continue;
                            end
                        else
                            cG = (cG+62)%136;
                            cT = 27.;
                        end
                    elseif cT < 10923. then
                        if cT < 10922 then
                            cG = (cG+"haeqbbuoq")%136;
                            cT = 192.;
                        elseif cT == 10922 then
                            local eh = d5;
                            cM:AddLabel("UI Keybind"):AddKeyPicker("MenuKeybind", { ["Default"] = "RightShift", ["Text"] = "UI Keybind", ["Toggles"] = true });
                            cM:AddToggle(eh[131], { ["Default"] = true, ["Callback"] = eh[95], ["Text"] = "Anti-AFK" });
                            cM:AddButton("Unload", "AntiAfk");
                            cN[eh[37]] = cJ["MenuKeybind"];
                            cN:OnUnload(eh[159.]);
                            ct:SetLibrary(cN);
                            ct:SetFolder("drizrtnxj");
                            ct:SaveDefault("https://raw.githubusercontent.com/deividcomsono/Obsidian/main/");
                            cl:SetLibrary(cN);
                            cl:IgnoreThemeSettings();
                            cl:SetIgnoreIndexes({ "MenuKeybind" });
                            cl:SetFolder("OuroborosHub/ChickenFarm");
                            cl:BuildConfigSection(cD["Settings"]);
                            ct:ApplyToTab(cD["Settings"]);
                            ct:LoadDefault();
                            cl:LoadAutoloadConfig();
                            local el = eh[15.]["spawn"];
                            eh[147.]("rylapb");
                            el = eh[15.]["spawn"];
                            eh[147.](eh[231.]);
                            el = eh[15.]["spawn"];
                            eh[147.](eh[200]);
                            el = eh[15.]["spawn"];
                            eh[147.](eh[178]);
                            el = eh[15.]["spawn"];
                            eh[147.](3581);
                            el = eh[15.]["spawn"];
                            eh[147.](eh[155]);
                            el = eh[15.]["spawn"];
                            eh[147.]("Network");
                            cT = 220;
                        else
                            cT = 11059;
                            continue;
                        end
                    else
                        cT = if cH <= 1 then 110 else 80;
                    end
                elseif cT < 10938. then
                    if cT < 10931 then
                        if cT < 10928 then
                            if cT < 10926. then
                                if cT < 10925 then
                                    cG = (cG+11)%136;
                                    cT = 72.;
                                else
                                    cT = 12.;
                                end
                            elseif cT < 10927 then
                                cT = 121;
                            elseif cT == 10927 then
                                cP = nil;
                                local eh = d5;
                                cP = 4-3.0;
                                cP = 0.0+1;
                                cT = 111.;
                            else
                                cT = 11000;
                                continue;
                            end
                        elseif cT < 10930 then
                            if cT < 10929. then
                                if cT == 10928 then
                                    local eh = d5;
                                    cE:AddToggle("AutoBuy", { ["Text"] = eh[107], ["Default"] = false });
                                    cE:AddDropdown("Buyables", { ["Text"] = "Buyables", [60807799] = cL, ["Default"] = {}, ["vdbrpwaw"] = true, ["Callback"] = eh[243.] });
                                    cE:AddDropdown("BuyChickensAmount", { ["Text"] = "Buy Chickens Amount", [60807799] = cB, ["Default"] = 1, ["vdbrpwaw"] = false, ["Callback"] = eh[286] });
                                    cC = cN["hmdwy"]:AddRightGroupbox("Merge & Upgrade", "trending-up");
                                    cT = 6.;
                                else
                                    cT = 10966;
                                    continue;
                                end
                            elseif cT == 10929. then
                                cT = if (cG*2+8)*"hwid"%3.0 == ((cG*2+8)*"hwid"+6.0)%3.0 then 49 else 92;
                            else
                                cT = 10936;
                                continue;
                            end
                        else
                            cT = 160;
                        end
                    elseif cT < 10935. then
                        if cT < 10933 then
                            if cT < 10932. then
                                cT = 76;
                            else
                                cT = 202;
                            end
                        elseif cT < 10934 then
                            local eh = d5;
                            cD:AddLabel("UI Keybind"):AddKeyPicker("MenuKeybind", { ["Default"] = "RightShift", ["Toggles"] = true, ["Text"] = "UI Keybind" });
                            cD:AddToggle(eh[131], { ["Text"] = "Anti-AFK", ["Default"] = true, ["Callback"] = eh[95] });
                            cD:AddButton("Unload", "AntiAfk");
                            cl[eh[37]] = ct["MenuKeybind"];
                            cl:OnUnload(eh[159.]);
                            cJ:SetLibrary(cl);
                            cJ:SetFolder("drizrtnxj");
                            cJ:SaveDefault("https://raw.githubusercontent.com/deividcomsono/Obsidian/main/");
                            cM:SetLibrary(cl);
                            cM:IgnoreThemeSettings();
                            cM:SetIgnoreIndexes({ "MenuKeybind" });
                            cM:SetFolder("OuroborosHub/ChickenFarm");
                            cM:BuildConfigSection(cN["Settings"]);
                            cJ:ApplyToTab(cN["Settings"]);
                            cJ:LoadDefault();
                            cM:LoadAutoloadConfig();
                            local em = eh[15.]["spawn"];
                            eh[147.]("rylapb");
                            em = eh[15.]["spawn"];
                            eh[147.](eh[231.]);
                            em = eh[15.]["spawn"];
                            eh[147.](eh[200]);
                            em = eh[15.]["spawn"];
                            eh[147.](eh[178]);
                            em = eh[15.]["spawn"];
                            eh[147.](3581);
                            em = eh[15.]["spawn"];
                            eh[147.](eh[155]);
                            em = eh[15.]["spawn"];
                            eh[147.]("Network");
                            cT = 220;
                        else
                            cC = cs["100"];
                            cT = 74;
                        end
                    elseif cT < 10937 then
                        if cT < 10936 then
                            if cT == 10935. then
                                cT = 52;
                            else
                                cT = 11053;
                                continue;
                            end
                        elseif cT == 10936 then
                            cT = 150.;
                        else
                            cT = 10980.;
                            continue;
                        end
                    else
                        cG = (cG+45.0)%136;
                        cT = 216.;
                    end
                elseif cT < 10947. then
                    if cT < 10942 then
                        if cT < 10940 then
                            if cT < 10939 then
                                if cT == 10938. then
                                    local eh = d5;
                                    cP = (vector.create((cG*4+3.0)%11+1, (cG*"hwid"+13)%13+1, (cG*"hwid"+11)%17+1));
                                    local en = vector.floor(cP)+vector.ceil(cP*eh[289]);
                                    cT = if vector.dot(en, en) == 0.0+3.0 then 1 else 201.;
                                else
                                    cT = 10959.;
                                    continue;
                                end
                            else
                                cT = 166;
                            end
                        elseif cT < 10941. then
                            if cT == 10940 then
                                local eh = d5;
                                cP = (vector.create((cG*1+3.0)%11+1, (cG*11+4)%13+1, (cG*5+8)%17+1));
                                cQ = (vector.create((cG*3.0+2)%11+1, (cG*"hwid"+"hvyt")%13+1, (cG*6.0+2)%17+1));
                                local eo = vector.dot(cP, cQ);
                                cT = if eo*eo <= vector.dot(cP, cP)*vector.dot(cQ, cQ) then 157 else 136;
                            else
                                cT = 11096;
                                continue;
                            end
                        else
                            cC = d5[148];
                            cT = 196;
                        end
                    elseif cT < 10944. then
                        if cT < 10943 then
                            cT = if cO <= 3.0 then 43 else 164;
                        else
                            cT = 172;
                        end
                    elseif cT < 10945 then
                        if cT == 10944. then
                            local eh = d5;
                            eh[174.], eh[121], eh[75.], eh[232], eh[177.], eh[113], eh[58], eh[10], eh[19], eh[229], eh[13], eh[143], eh[43], eh[294.], eh[78.], eh[225.] = 96.0, "Size", "NoUI", eh[174.], "Farm", 3431, eh[232], 81.0, 3581, "Buy Chickens", "qtansbp", "Right", "Title", "Toggles", "rylapb", "xdkpgxhgwy";
                            eh[285.], eh[128], eh[218], eh[131], eh[31], eh[175], eh[12.], eh[261.], eh[122], eh[283], eh[106], eh[284], eh[207.] = "vdbrpwaw", 1109999133.0, "Auto Collect Cash", eh[207.], "Multi", "100", "Join Discord to Make Money", "ossq", "Eggs", "addons/SaveManager.lua", "Deposit Eggs", "hizlqdd", "AntiAfk";
                            eh[177.], eh[268], eh[127], eh[189.], eh[39.], eh[272], eh[240.], eh[290], eh[62], eh[217], eh[184], eh[279.], eh[4], eh[144.], eh[33.], eh[10], eh[66.] = 113, "Buy Chickens", "OuroborosHub", "hvyt", "Size", "jsfujxkbfze", 9.0, "hwid", "wrench", eh[62], 7, "EggMultiplierPart", "Values", "https://raw.githubusercontent.com/deividcomsono/Obsidian/main/", eh[33.], "haeqbbuoq", "drizrtnxj";
                            eh[157], eh[278], eh[10], eh[112], eh[227], eh[20], eh[107], eh[285.], eh[248], eh[167], eh[257], eh[102.], eh[45.], eh[229], eh[128], eh[81.], eh[14], eh[90.], eh[218], eh[53] = 1109999133.0, 7087336, eh[227], 3900.0, "Auto Buy", 3891925009, 686, eh[10], "AutoDeposit", "Deposit Eggs", eh[157], "Network", 16687805, "Size", 2374617845, "100", "rylapb", 2762, "Upgrades", "LocalPlayer";
                            eh[58], eh[76], eh[145], eh[6.], eh[176], eh[290], eh[115], eh[155], eh[87.], eh[77], eh[46] = "qiob", eh[6.], 15.0, "1", "Collect Cash", 60807799, eh[58], eh[155], "Values", "Mint", 3581;
                            eh[266], eh[219.], eh[155], eh[156.], eh[242], eh[239], eh[241] = "navvixcbs", "Main", eh[155], "hmdwy", "kzoqhbjtxs", "https://discord.gg/ehKVq7pf7v", eh[242];
                            cC, cH, cw, cs, cE, cl, cJ, cM, cx, ct, cF, cm, cj, cB, cy, cL, cq, co, cK, ch, cD, cN, cA, cu, cp, cn, cz, cr, ci, cv, cI, cG = nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil;
                            cG = 0.0;
                            cT = 120.;
                        else
                            cT = 11023;
                            continue;
                        end
                    elseif cT < 10946 then
                        cV = false;
                        for aJ, aK in cN do
                            cW = aJ;
                            cY = aK;
                            local cX = cW;
                            local cZ = cY;
                            local cU = nil;
                            local eh = d5;
                            cU = 2;
                            while true do
                                if cU < 1 then
                                    break;
                                elseif cU < 2 then
                                    cV = true;
                                    cU = 0.0;
                                else
                                    cI(cZ);
                                    cU = 0.0;
                                end
                            end
                            if cV then
                                break;
                            end
                        end
                        cG, cE, cC, cD, ck, cF = nil, nil, nil, nil, nil, nil;
                        cF = 7;
                        cT = 116;
                    elseif cT == 10946 then
                        cT = if cG*60807799+3.0+7 >= cG*60807799+3.0+7+4 then 199 else 217;
                    else
                        cT = 11015;
                        continue;
                    end
                elseif cT < 10950. then
                    if cT < 10949 then
                        if cT < 10948 then
                            if cT == 10947. then
                                cG = cN["Main"]:AddLeftGroupbox("Farm", "wheat");
                                cT = 39.;
                            else
                                cT = 11017;
                                continue;
                            end
                        else
                            cT = 114.;
                        end
                    else
                        local eh = d5;
                        cH = require(cm["Paper"]);
                        cF = cH["Network"];
                        cT = 141.;
                    end
                elseif cT < 10952 then
                    if cT < 10951 then
                        if cT == 10950. then
                            cT = 40;
                        else
                            cT = 10919;
                            continue;
                        end
                    elseif cT == 10951 then
                        cT = 148;
                    else
                        cT = 13822;
                        continue;
                    end
                else
                    cT = 213.;
                end
            elseif cT < 10981 then
                if cT < 10967 then
                    if cT < 10960 then
                        if cT < 10957 then
                            if cT < 10955 then
                                if cT < 10954 then
                                    if cT == 10953. then
                                        cP = nil;
                                        local eh = d5;
                                        cP = 6.0-4;
                                        cP = 3.0-2;
                                        cP = 0.0+1;
                                        cT = 29;
                                    else
                                        cT = 10949;
                                        continue;
                                    end
                                elseif cT == 10954 then
                                    cT = 186.;
                                else
                                    cT = 11060;
                                    continue;
                                end
                            elseif cT < 10956. then
                                cO = nil;
                                local eh = d5;
                                cO = 3.0-2;
                                cO = 0.0+1;
                                cO = 3.0-2;
                                cO = 0.0+1;
                                cO = 2-1;
                                cO = 0.0+1;
                                cT = 109;
                            else
                                local ep = bit32.rrotate(bit32.bxor(bit32.lrotate(cG, 18.0), string.byte(tostring(cm))), 29);
                                cT = if bit32.bxor(bit32.bxor(bit32.bxor(bit32.bxor(bit32.band(ep, 1109999133.0), 1393569622), (bit32.bxor(bit32.band(ep, 3184968162.0), 3891925009))), 1393569622), 3891925009) == ep then 62 else 54.;
                            end
                        elseif cT < 10959. then
                            if cT < 10958 then
                                if cT == 10957 then
                                    cT = if (cG*71+81.0)%136 == 13 then 174. else 103;
                                else
                                    cT = 11076.;
                                    continue;
                                end
                            else
                                cT = if cO <= 10 then 153. else 115;
                            end
                        else
                            cw = d5[242]:GetService("VirtualUser");
                            cT = 59;
                        end
                    elseif cT < 10964 then
                        if cT < 10962. then
                            if cT < 10961 then
                                cE = "https://raw.githubusercontent.com/deividcomsono/Obsidian/main/";
                                cT = 193;
                            else
                                cP = nil;
                                local eh = d5;
                                cP = 7-5;
                                cP = 4-3.0;
                                cP = 4-3.0;
                                cP = 0.0+1;
                                cT = 78.;
                            end
                        elseif cT < 10963 then
                            cT = 4;
                        elseif cT == 10963 then
                            cP = nil;
                            cP = 3.0-2;
                            cT = 96.;
                        else
                            cT = 11042;
                            continue;
                        end
                    elseif cT < 10966 then
                        if cT < 10965. then
                            cT = 101;
                        else
                            cG = (cG+96.0)%136;
                            cT = 11;
                        end
                    else
                        cH = nil;
                        local eh = d5;
                        cH = 4-3.0;
                        cH = 3.0-2;
                        cH = 2-1;
                        cH = 0.0+1;
                        cT = 119;
                    end
                elseif cT < 10974. then
                    if cT < 10971. then
                        if cT < 10969 then
                            if cT < 10968. then
                                if cT == 10967 then
                                    local eh = d5;
                                    cP = { "oeep", "cojcwjjk", "xpghaetd", "ybk", "nmkittx", "hvyt", "kzoqhbjtxs", "qtansbp", "bbsaoox", "rkamslf", "dfzgrac", "gljx" };
                                    local eq = cG;
                                    cQ = cP[eq%12.0+1];
                                    cT = if cQ:len() <= cQ:gsub("(.)", "%1%1", eq%3.0%2+1):len() then 133 else 168.;
                                else
                                    cT = 11115.;
                                    continue;
                                end
                            elseif cT == 10968. then
                                cT = 135.;
                            else
                                cT = 10995.;
                                continue;
                            end
                        elseif cT < 10970 then
                            cT = 53;
                        else
                            cG = (cG+79)%136;
                            cT = 2;
                        end
                    elseif cT < 10973 then
                        if cT < 10972 then
                            cT = if cO <= 13 then 70 else 125;
                        elseif cT == 10972 then
                            cI = d5[148];
                            cT = 196;
                        else
                            cT = 10922;
                            continue;
                        end
                    else
                        cT = if cH <= 4 then 57. else 151;
                    end
                elseif cT < 10978 then
                    if cT < 10976 then
                        if cT < 10975 then
                            if cT == 10974. then
                                cF = (cF+16)%20;
                                cT = 178;
                            else
                                cT = 11049.;
                                continue;
                            end
                        elseif cT == 10975 then
                            cT = 155;
                        else
                            cT = 11106.;
                            continue;
                        end
                    elseif cT < 10977. then
                        cG = (cG+11)%136;
                        cT = 36.;
                    elseif cT == 10977. then
                        cO = (cG*14+6.0)%17+1;
                        cT = 71;
                    else
                        cT = 11054;
                        continue;
                    end
                elseif cT < 10980. then
                    if cT < 10979 then
                        cG = (cG+28)%136;
                        cT = 14;
                    elseif cT == 10979 then
                        cT = if cO <= 6.0 then 81. else 19;
                    else
                        cT = 11072;
                        continue;
                    end
                elseif cT == 10980. then
                    cT = 24.;
                else
                    cT = 12189.;
                    continue;
                end
            elseif cT < 10996 then
                if cT < 10988 then
                    if cT < 10985 then
                        if cT < 10983. then
                            if cT < 10982 then
                                if cT == 10981 then
                                    cC = "https://raw.githubusercontent.com/deividcomsono/Obsidian/main/";
                                    cT = 193;
                                else
                                    cT = 11063;
                                    continue;
                                end
                            else
                                cT = 21.;
                            end
                        elseif cT < 10984 then
                            if cT == 10983. then
                                cG = (cG+45.0)%136;
                                cT = 10;
                            else
                                cT = 10910;
                                continue;
                            end
                        else
                            local eh = d5;
                            cF = require(cH["Paper"]);
                            cm = cF["Network"];
                            cT = 141.;
                        end
                    elseif cT < 10987 then
                        if cT < 10986. then
                            if cT == 10985 then
                                cP = nil;
                                local eh = d5;
                                cP = 7-6.0;
                                cP = 0.0+1;
                                cT = 88;
                            else
                                cT = 10965.;
                                continue;
                            end
                        else
                            cl = cD:CreateWindow({ ["Icon"] = 18657887261, ["Footer"] = "Ouroboros Hub", ["Title"] = "Chicken Farm", ["NotifySide"] = "Right", ["Size"] = d5[224]["fromOffset"](900.0, 640) });
                            cT = 203;
                        end
                    else
                        break;
                    end
                elseif cT < 10993 then
                    if cT < 10990 then
                        if cT < 10989. then
                            if cT == 10988 then
                                cT = 7;
                            else
                                cT = 10961;
                                continue;
                            end
                        elseif cT == 10989. then
                            cT = 159.;
                        else
                            cT = 11104;
                            continue;
                        end
                    elseif cT < 10991 then
                        if cT == 10990 then
                            cT = 194;
                        else
                            cT = 10993;
                            continue;
                        end
                    elseif cT < 10992. then
                        cT = 130;
                    else
                        cP = nil;
                        local eh = d5;
                        cP = 8-7;
                        cP = 0.0+1;
                        cP = 10-7;
                        cP = 0.0+3.0;
                        cT = 212;
                    end
                elseif cT < 10995. then
                    if cT < 10994 then
                        cT = 67;
                    elseif cT == 10994 then
                        cT = if cO <= 5 then 61 else 132.;
                    else
                        cT = 10949;
                        continue;
                    end
                elseif cT == 10995. then
                    cT = 102.;
                else
                    cT = 10997;
                    continue;
                end
            elseif cT < 11003 then
                if cT < 11000 then
                    if cT < 10998. then
                        if cT < 10997 then
                            if cT == 10996 then
                                cT = 38;
                            else
                                cT = 11068;
                                continue;
                            end
                        elseif cT == 10997 then
                            cT = if true then 140 else 172;
                        else
                            cT = 10926.;
                            continue;
                        end
                    elseif cT < 10999 then
                        if cT == 10998. then
                            local eh = d5;
                            cH = (vector.create((cF*1+1)%11+1, (cF*5+12.0)%13+1, (cF*11+9.0)%17+1));
                            cI = (vector.create((cF*5+6.0)%11+1, (cF*8+13)%13+1, (cF*3.0+14)%17+1));
                            cO = (vector.create((cF*2+9.0)%11+1, (cF*9.0+7)%13+1, (cF*11+6.0)%17+1));
                            cT = if vector.dot(vector.cross(cH, cI), cO) == vector.dot(vector.cross(cI, cO), cH) then 34 else 64;
                        else
                            cT = 11100.;
                            continue;
                        end
                    else
                        local eh = d5;
                        cH = { "vdbrpwaw", "slboji", "rylapb", "zvbpsyda", "lmp", "wnv", "qiob", "ossq" };
                        cT = if cH[(cF*63.0+96.0)%8+1] <= cH[(cF*63.0+96.0)%8+1] then 189. else 104;
                    end
                elseif cT < 11002 then
                    if cT < 11001. then
                        if cT == 11000 then
                            cT = if cO <= 12.0 then 51. else 106;
                        else
                            cT = 11024;
                            continue;
                        end
                    elseif cT == 11001. then
                        cT = if true then 113 else 126.;
                    else
                        cT = 11027;
                        continue;
                    end
                else
                    cP = nil;
                    cP = 3.0-2;
                    cT = 177.;
                end
            elseif cT < 11006 then
                if cT < 11005 then
                    if cT < 11004. then
                        cT = 202;
                    else
                        cH = (cF*1+4)%5+1;
                        cT = 25;
                    end
                else
                    local eh = d5;
                    cP = (vector.create((cG*5+4)%11+1, (cG*7+6.0)%13+1, (cG*4+17)%17+1));
                    cQ = (vector.create((cG*7+4)%11+1, (cG*10+6.0)%13+1, (cG*6.0+7)%17+1));
                    cR = (vector.create((cG*3.0+9.0)%11+1, (cG*6.0+12.0)%13+1, (cG*13+14)%17+1));
                    cS = (vector.create((cG*2+3.0)%5+1, (cG*4+3.0)%7+1, (cG*3.0+2)%9.0+1));
                    cT = if vector.dot(vector.cross(cP, (vector.cross(cQ, cR))), cS) == vector.dot(cQ*vector.dot(cP, cR)-cR*vector.dot(cP, cQ), cS) then 207. else 100;
                end
            elseif cT < 11008 then
                if cT < 11007. then
                    local eh = d5;
                    cP = (vector.create((cG*3.0+4)%11+1, (cG*11+5)%13+1, (cG*5+15.0)%17+1));
                    cQ = (vector.create((cG*3.0+3.0)%11+1, (cG*8+12.0)%13+1, (cG*1+13)%17+1));
                    local er = vector.cross(cP, cQ);
                    local es = vector.dot(cP, cQ);
                    cT = if vector.dot(er, er)+es*es == vector.dot(cP, cP)*vector.dot(cQ, cQ) then 85 else 63.;
                elseif cT == 11007. then
                    cT = 75.;
                else
                    cT = 11031.;
                    continue;
                end
            elseif cT == 11008 then
                local eh = d5;
                cO = { "hmdwy", "sqarxaqexa", "ukkhnarkbknn", "xdkpgxhgwy", "dym", "vorb", "ilmjh", "cfpa", "lyjhk", "bdjgiu", "xywipyj", "yvo", "uffvqjdjgly", "pypgusigdkzn" };
                cT = if cO[(cG*88+12.0)%14+1] <= cO[(cG*88+12.0)%14+1] then 42. else 87.;
            else
                cT = 10956.;
                continue;
            end
        elseif cT < 11064. then
            if cT < 11037. then
                if cT < 11023 then
                    if cT < 11016. then
                        if cT < 11013. then
                            if cT < 11011 then
                                if cT < 11010. then
                                    cT = 215;
                                elseif cT == 11010. then
                                    cT = 166;
                                else
                                    cT = 10967;
                                    continue;
                                end
                            elseif cT < 11012 then
                                cP = nil;
                                local eh = d5;
                                cP = 5-4;
                                cP = 0.0+1;
                                cT = 0.;
                            elseif cT == 11012 then
                                cP = nil;
                                local eh = d5;
                                cP = 2-1;
                                cP = 3.0-2;
                                cP = 0.0+1;
                                cT = 93.;
                            else
                                cT = 11115.;
                                continue;
                            end
                        elseif cT < 11015 then
                            if cT < 11014 then
                                local eh = d5;
                                cC:AddToggle("AutoBuy", { ["Text"] = "Auto Buy", ["Default"] = false });
                                cC:AddDropdown("Buyables", { ["Multi"] = true, ["Callback"] = eh[243.], ["Text"] = "Buyables", ["Default"] = {}, ["Values"] = cE });
                                cC:AddDropdown("BuyChickensAmount", { ["Text"] = "Buy Chickens Amount", ["Callback"] = eh[286], ["Multi"] = false, ["Default"] = 1, ["Values"] = cL });
                                cN = cB["Main"]:AddRightGroupbox("Merge & Upgrade", "trending-up");
                                cT = 6.;
                            else
                                cT = 120.;
                            end
                        elseif cT == 11015 then
                            cT = 187;
                        else
                            cT = 11087;
                            continue;
                        end
                    elseif cT < 11020 then
                        if cT < 11018 then
                            if cT < 11017 then
                                local eh = d5;
                                cP = { "wzsafot", "nmcdrjpwru", "plspt", "hizlqdd", "xpqh", "yztacspns", "ontmrmvgm" };
                                local et = cG;
                                cQ = cP[et%7+1];
                                cT = if cQ:len() >= cQ:gsub("(.)", "%1%1", et%3.0%2+1):len() then 183. else 84.;
                            elseif cT == 11017 then
                                cx = d5[242]:GetService("Players");
                                cT = 134;
                            else
                                cT = 10915;
                                continue;
                            end
                        elseif cT < 11019. then
                            if cT == 11018 then
                                cT = 89;
                            else
                                cT = 11095;
                                continue;
                            end
                        else
                            cT = 205;
                        end
                    elseif cT < 11022. then
                        if cT < 11021 then
                            if cT == 11020 then
                                cT = 182;
                            else
                                cT = 11029;
                                continue;
                            end
                        else
                            local eh = d5;
                            cP = (vector.create((cG*6.0+5)%11+1, (cG*11+3.0)%13+1, (cG*12.0+9.0)%17+1));
                            cQ = (vector.create((cG*7+2)%11+1, (cG*9.0+8)%13+1, (cG*9.0+9.0)%17+1));
                            cR = (vector.create((cG*3.0+1)%5+1, (cG*1+2)%7+1, (cG*3.0+4)%9.0+1));
                            cT = if math.abs((vector.angle(cP, cQ, cR)))-math.abs((vector.angle(cQ, cP, cR))) == 0.0+4 then 3. else 158;
                        end
                    elseif cT == 11022. then
                        cT = 122;
                    else
                        cT = 11094.;
                        continue;
                    end
                elseif cT < 11030 then
                    if cT < 11027 then
                        if cT < 11025. then
                            if cT < 11024 then
                                if cT == 11023 then
                                    cT = if cO <= 8 then 98 else 154;
                                else
                                    cT = 11022.;
                                    continue;
                                end
                            elseif cT == 11024 then
                                cT = if cG*16687805+11+3.0 <= cG*16687805+11+3.0+4 then 68 else 210.;
                            else
                                cT = 11054;
                                continue;
                            end
                        elseif cT < 11026 then
                            cD = { ["Main"] = cN:AddTab("Main", "egg"), ["Settings"] = cN:AddTab("Settings", "settings") };
                            cT = 139;
                        else
                            cT = if (cG*3.0+4)*5%4 == ((cG*3.0+4)*5+8)%4 then 145 else 176;
                        end
                    elseif cT < 11029 then
                        if cT < 11028. then
                            if cT == 11027 then
                                local eh = d5;
                                cE = loadstring(eh[242]:HttpGet(cM .. "addons/ThemeManager.lua"))();
                                cl = loadstring(eh[242]:HttpGet(cM .. "addons/SaveManager.lua"))();
                                ct = cJ["Toggles"];
                                cx = cJ["Options"];
                                cT = 86;
                            else
                                cT = 10999;
                                continue;
                            end
                        else
                            cT = 73;
                        end
                    elseif cT == 11029 then
                        cT = if cO <= 7 then 15. else 219.;
                    else
                        cT = 11045;
                        continue;
                    end
                elseif cT < 11034. then
                    if cT < 11032 then
                        if cT < 11031. then
                            if cT == 11030 then
                                ch = { "Upgrade Process Level", "Upgrade Buy Tier Level" };
                                cK = {};
                                cT = 56;
                            else
                                cT = 10937;
                                continue;
                            end
                        elseif cT == 11031. then
                            cG = (cG+45.0)%136;
                            cT = 191;
                        else
                            cT = 10978;
                            continue;
                        end
                    elseif cT < 11033 then
                        if cT == 11032 then
                            local eh = d5;
                            cj = "https://discord.gg/ehKVq7pf7v";
                            cB = { "1", "5", "25", "100" };
                            cy = 1;
                            cL = { "Buy Chickens", "Merge Chickens", "Upgrade Process Level", "Upgrade Buy Tier Level", "Claim Group Reward" };
                            cT = 8;
                        else
                            cT = 10962.;
                            continue;
                        end
                    elseif cT == 11033 then
                        cs = cC["LocalPlayer"];
                        cT = 74;
                    else
                        cT = 11028.;
                        continue;
                    end
                elseif cT < 11036 then
                    if cT < 11035 then
                        cF = (cF+1)%20;
                        cT = 108.;
                    else
                        cT = 9.;
                    end
                elseif cT == 11036 then
                    cT = 91;
                else
                    cT = 10968.;
                    continue;
                end
            elseif cT < 11051 then
                if cT < 11044 then
                    if cT < 11041 then
                        if cT < 11039 then
                            if cT < 11038 then
                                cI = nil;
                                local eh = d5;
                                cI = 5-4;
                                cI = 2-1;
                                cI = 3.0-2;
                                cT = 77;
                            else
                                cT = 67;
                            end
                        elseif cT < 11040. then
                            if cT == 11039 then
                                cT = if cO <= 16 then 5 else 162.;
                            else
                                cT = 10931;
                                continue;
                            end
                        elseif cT == 11040. then
                            local eh = d5;
                            cI = (vector.create((cF*1+4)%11+1, (cF*11+11)%13+1, (cF*10+3.0)%17+1));
                            cO = (vector.create((cF*6.0+8)%11+1, (cF*6.0+9.0)%13+1, (cF*12.0+4)%17+1));
                            cP = (vector.create((cF*4+3.0)%5+1, (cF*3.0+7)%7+1, (cF*4+2)%9.0+1));
                            cT = if math.abs((vector.angle(cI, cO, cP)))-math.abs((vector.angle(cO, cI, cP))) == 0.0+4 then 44 else 170;
                        else
                            cT = 11112.;
                            continue;
                        end
                    elseif cT < 11043. then
                        if cT < 11042 then
                            cT = 82;
                        elseif cT == 11042 then
                            cT = if (cF*1+3.0)*9.0%4 == ((cF*1+3.0)*9.0+8)%4 then 184 else 195.;
                        else
                            cT = 10904;
                            continue;
                        end
                    else
                        cG = (cG+96.0)%136;
                        cT = 214;
                    end
                elseif cT < 11048 then
                    if cT < 11046. then
                        if cT < 11045 then
                            cT = 76;
                        else
                            cT = 149;
                        end
                    elseif cT < 11047 then
                        cT = if cO <= 9.0 then 35 else 198.;
                    else
                        cT = 47;
                    end
                elseif cT < 11050 then
                    if cT < 11049. then
                        if cT == 11048 then
                            cT = if cO <= 14 then 181 else 190;
                        else
                            cT = 10985;
                            continue;
                        end
                    elseif cT == 11049. then
                        local eh = d5;
                        cz = eh[3.];
                        cr = eh[32];
                        ci = function()
    local ds, du, dv, dw = nil, nil, nil, nil;
    local dt = nil;
    dt = 1;
    while true do
        dt = 11832.-dt;
        do
            if dt < 11832. then
                if dt < 10223 then
                    break;
                elseif dt < 11831 then
                    break;
                elseif dt == 11831 then
                    dv = false;
                    for at in ch do
                        dw = at;
                        local dx = dw;
                        local du = nil;
                        local eu = d5;
                        du = 0.0;
                        while true do
                            if du < 3. then
                                if du < 1 then
                                    ds = cl["Unloaded"];
                                    du = if ds then 5 else 6.0;
                                elseif du < 2 then
                                    dv = true;
                                    du = 2;
                                else
                                    break;
                                end
                            elseif du < 5 then
                                if du < 4 then
                                    du = 1;
                                else
                                    eu[94](function()
    cm["InvokeServer"](dx);
end);
                                    local ev = eu[15.]["wait"];
                                    eu[187](0.15);
                                    du = 2;
                                end
                            elseif du < 6. then
                                du = if ds then 3.0 else 4;
                            else
                                ds = not cx["AutoUpgrade"]["Value"];
                                du = 5;
                            end
                        end
                        if dv then
                            break;
                        end
                    end
                    dt = 0.;
                else
                    dt = 11832.;
                    continue;
                end
            else
                break;
            end
        end
    end
end;
                        cT = 18.;
                    else
                        cT = 11107;
                        continue;
                    end
                elseif cT == 11050 then
                    cT = 37;
                else
                    cT = 11062;
                    continue;
                end
            elseif cT < 11058. then
                if cT < 11055. then
                    if cT < 11053 then
                        if cT < 11052. then
                            local ew = bit32.rrotate(bit32.bxor(3145728, string.byte(tostring(ck))), 5);
                            cT = if bit32.bxor(bit32.bxor(bit32.bxor(bit32.bxor(bit32.band(ew, 2517909275), 2374617845), (bit32.bxor(bit32.band(ew, 1777058020), 2283630668))), 2374617845), 2283630668) ~= ew then 32 else 65;
                        elseif cT == 11052. then
                            local eh = d5;
                            cG:AddToggle("AutoCollectEggs", { ["Text"] = "Auto Collect Eggs", ["Default"] = false });
                            cG:AddLabel("Auto Collect works, but collected eggs stay on the conveyor visually. Enable Remove Egg Models to clear them locally.", true);
                            cG:AddToggle("RemoveEggModels", { ["Text"] = "Remove Egg Models", ["Default"] = false });
                            cG:AddToggle("AutoDeposit", { ["Text"] = "Auto Deposit", ["Default"] = false });
                            cG:AddSlider("MinimumEggMultiplier", { ["Text"] = "Minimum Egg Multiplier", ["Default"] = 1.01, ["Min"] = 0.7, ["Max"] = 2, ["Rounding"] = 2, ["Suffix"] = "x" });
                            cG:AddToggle("AutoCollectCash", { ["Text"] = "Auto Collect Cash", ["Default"] = false });
                            cE = cN["Main"]:AddRightGroupbox("Auto Buy", "shopping-cart");
                            cT = 83;
                        else
                            cT = 10940;
                            continue;
                        end
                    elseif cT < 11054 then
                        if cT == 11053 then
                            local eh = d5;
                            cD:AddToggle("AutoMerge", { ["Text"] = "Auto Merge", ["Default"] = false });
                            cD:AddToggle("AutoUpgrade", { ["Text"] = "Auto Upgrade", ["Default"] = false });
                            cD:AddDropdown("Upgrades", { ["Callback"] = eh[169], ["Default"] = {}, ["Values"] = cC, ["Text"] = "Upgrades", ["Multi"] = true });
                            cN = cK["Settings"]:AddLeftGroupbox("Menu", "wrench");
                            cT = 143;
                        else
                            cT = 10904;
                            continue;
                        end
                    elseif cT == 11054 then
                        local eh = d5;
                        cL = "https://discord.gg/ehKVq7pf7v";
                        cj = { "100", "25", "1", "5" };
                        cB = 1;
                        cy = { "Upgrade Buy Tier Level", "Upgrade Process Level", "Claim Group Reward", "Merge Chickens", "Buy Chickens" };
                        cT = 8;
                    else
                        cT = 10972;
                        continue;
                    end
                elseif cT < 11057 then
                    if cT < 11056 then
                        if cT == 11055. then
                            local eh = d5;
                            cA = eh[42.];
                            cu = eh[58];
                            cp = eh[6.];
                            cn = eh[228.];
                            cT = 204.;
                        else
                            cT = 11006;
                            continue;
                        end
                    elseif cT == 11056 then
                        cT = 175;
                    else
                        cT = 10945;
                        continue;
                    end
                elseif cT == 11057 then
                    cT = 53;
                else
                    cT = 11017;
                    continue;
                end
            elseif cT < 11061. then
                if cT < 11060 then
                    if cT < 11059 then
                        if cT == 11058. then
                            cG = (cG+130)%136;
                            cT = 97;
                        else
                            cT = 11033;
                            continue;
                        end
                    else
                        cT = 122;
                    end
                elseif cT == 11060 then
                    cT = 118;
                else
                    cT = 10979;
                    continue;
                end
            elseif cT < 11063 then
                if cT < 11062 then
                    if cT == 11061. then
                        cG = (cG+11)%136;
                        cT = 200;
                    else
                        cT = 11067.;
                        continue;
                    end
                else
                    cN = d5[242]:GetService("ReplicatedStorage");
                    cT = 197;
                end
            else
                local eh = d5;
                cn = eh[42.];
                cA = eh[58];
                cu = eh[6.];
                cp = eh[228.];
                cT = 204.;
            end
        elseif cT < 11092 then
            if cT < 11078 then
                if cT < 11071 then
                    if cT < 11068 then
                        if cT < 11066 then
                            if cT < 11065 then
                                cT = 13;
                            elseif cT == 11065 then
                                cT = 218;
                            else
                                cT = 10911.;
                                continue;
                            end
                        elseif cT < 11067. then
                            if cT == 11066 then
                                cT = 179;
                            else
                                cT = 11000;
                                continue;
                            end
                        else
                            cD = cl:CreateWindow({ ["Title"] = "Chicken Farm", ["Footer"] = "Ouroboros Hub", ["Icon"] = 18657887261, ["NotifySide"] = "Right", ["Size"] = d5[224]["fromOffset"](900.0, 640) });
                            cT = 203;
                        end
                    elseif cT < 11070. then
                        if cT < 11069 then
                            cN = { ["Main"] = cD:AddTab("Main", "egg"), ["Settings"] = cD:AddTab("Settings", "settings") };
                            cT = 139;
                        elseif cT == 11069 then
                            cT = 9.;
                        else
                            cT = 11010.;
                            continue;
                        end
                    elseif cT == 11070. then
                        cT = if cO <= 11 then 128 else 41;
                    else
                        cT = 3218;
                        continue;
                    end
                elseif cT < 11075 then
                    if cT < 11073. then
                        if cT < 11072 then
                            cq = { ["Buy Chickens"] = d5[258.], ["Merge Chickens"] = d5[140], ["Upgrade Process Level"] = d5[251], ["Upgrade Buy Tier Level"] = d5[174.], ["Claim Group Reward"] = d5[33.] };
                            co = {};
                            cT = 180.;
                        else
                            cI = nil;
                            local eh = d5;
                            cI = 2-1;
                            cI = 0.0+1;
                            cI = 3.0-1;
                            cT = 144.;
                        end
                    elseif cT < 11074 then
                        if cT == 11073. then
                            cN = cG["Main"]:AddLeftGroupbox("Farm", "wheat");
                            cT = 39.;
                        else
                            cT = 11002;
                            continue;
                        end
                    else
                        cT = 221;
                    end
                elseif cT < 11077 then
                    if cT < 11076. then
                        if cT == 11075 then
                            cK = { "Upgrade Process Level", "Upgrade Buy Tier Level" };
                            ch = {};
                            cT = 56;
                        else
                            cT = 13399;
                            continue;
                        end
                    elseif cT == 11076. then
                        cP = nil;
                        local eh = d5;
                        cP = 4-2;
                        cP = 1+1;
                        cP = 6.0-4;
                        cP = 4-2;
                        cT = 117.;
                    else
                        cT = 10930;
                        continue;
                    end
                else
                    cT = 185;
                end
            elseif cT < 11085. then
                if cT < 11082. then
                    if cT < 11080 then
                        if cT < 11079. then
                            if cT == 11078 then
                                cF = (cF+1)%20;
                                cT = 26;
                            else
                                cT = 11096;
                                continue;
                            end
                        else
                            cT = 21.;
                        end
                    elseif cT < 11081 then
                        cT = 169;
                    elseif cT == 11081 then
                        cT = 89;
                    else
                        cT = 11053;
                        continue;
                    end
                elseif cT < 11084 then
                    if cT < 11083 then
                        if cT == 11082. then
                            cT = 123.;
                        else
                            cT = 10937;
                            continue;
                        end
                    elseif cT == 11083 then
                        local eh = d5;
                        cC:AddToggle("AutoMerge", { ["Text"] = "Auto Merge", ["Default"] = false });
                        cC:AddToggle("AutoUpgrade", { ["Text"] = "Auto Upgrade", ["Default"] = false });
                        cC:AddDropdown("Upgrades", { ["Text"] = "Upgrades", ["Values"] = cK, ["Default"] = {}, ["Multi"] = true, ["Callback"] = eh[169] });
                        cD = cN["Settings"]:AddLeftGroupbox("Menu", "wrench");
                        cT = 143;
                    else
                        cT = 13399;
                        continue;
                    end
                else
                    cT = 116;
                end
            elseif cT < 11089 then
                if cT < 11087 then
                    if cT < 11086 then
                        local eh = d5;
                        cE:AddToggle("AutoCollectEggs", { ["Text"] = "Auto Collect Eggs", ["Default"] = false });
                        cE:AddLabel("Auto Collect works, but collected eggs stay on the conveyor visually. Enable Remove Egg Models to clear them locally.", true);
                        cE:AddToggle("RemoveEggModels", { ["Text"] = "Remove Egg Models", ["Default"] = false });
                        cE:AddToggle("AutoDeposit", { ["Text"] = "Auto Deposit", ["Default"] = false });
                        cE:AddSlider("MinimumEggMultiplier", { ["Text"] = "Minimum Egg Multiplier", ["Min"] = 0.7, ["Rounding"] = 2, ["Suffix"] = "x", ["Max"] = 2, ["Default"] = 1.01 });
                        cE:AddToggle("AutoCollectCash", { ["Text"] = "Auto Collect Cash", ["Default"] = false });
                        cN = cG["Main"]:AddRightGroupbox("Auto Buy", "shopping-cart");
                        cT = 83;
                    elseif cT == 11086 then
                        cT = 161;
                    else
                        cT = 11025.;
                        continue;
                    end
                elseif cT < 11088. then
                    if cT == 11087 then
                        co = { ["Upgrade Process Level"] = d5[251], ["Buy Chickens"] = d5[258.], ["Merge Chickens"] = d5[140], ["Claim Group Reward"] = d5[33.], ["Upgrade Buy Tier Level"] = d5[174.] };
                        cq = {};
                        cT = 180.;
                    else
                        cT = 10945;
                        continue;
                    end
                else
                    cT = if cO <= 4 then 129. else 211;
                end
            elseif cT < 11091. then
                if cT < 11090 then
                    if cT == 11089 then
                        local eh = d5;
                        cJ = loadstring(eh[242]:HttpGet(cE .. "addons/ThemeManager.lua"))();
                        cM = loadstring(eh[242]:HttpGet(cE .. "addons/SaveManager.lua"))();
                        cx = cl["Toggles"];
                        ct = cl["Options"];
                        cT = 86;
                    else
                        cT = 10957;
                        continue;
                    end
                else
                    cT = 182;
                end
            else
                cT = 155;
            end
        elseif cT < 11106. then
            if cT < 11099 then
                if cT < 11096 then
                    if cT < 11094. then
                        if cT < 11093 then
                            if cT == 11092 then
                                cT = if cH <= 3.0 then 165. else 45.;
                            else
                                cT = 10903;
                                continue;
                            end
                        elseif cT == 11093 then
                            cT = if cO <= 1 then 31 else 105.;
                        else
                            cT = 10993;
                            continue;
                        end
                    elseif cT < 11095 then
                        if cT == 11094. then
                            cI = nil;
                            local eh = d5;
                            cI = 2-1;
                            cI = 0.0+1;
                            cT = 66.;
                        else
                            cT = 10905.;
                            continue;
                        end
                    else
                        cH = d5[242]:GetService("ReplicatedStorage");
                        cT = 197;
                    end
                elseif cT < 11098 then
                    if cT < 11097. then
                        if cT == 11096 then
                            cT = 48.;
                        else
                            cT = 11041;
                            continue;
                        end
                    elseif cT == 11097. then
                        cT = 187;
                    else
                        cT = 11018;
                        continue;
                    end
                else
                    cP = nil;
                    local eh = d5;
                    cP = 5-4;
                    cP = 5-4;
                    cT = 112;
                end
            elseif cT < 11103. then
                if cT < 11101 then
                    if cT < 11100. then
                        if cT == 11099 then
                            cG = (cG+28)%136;
                            cT = 124;
                        else
                            cT = 10955;
                            continue;
                        end
                    else
                        cT = 218;
                    end
                elseif cT < 11102 then
                    if cT == 11101 then
                        cP = nil;
                        local eh = d5;
                        cP = 2-1;
                        cP = 4-3.0;
                        cT = 171.;
                    else
                        cT = 10902.;
                        continue;
                    end
                else
                    cT = 138.;
                end
            elseif cT < 11105 then
                if cT < 11104 then
                    if cT == 11103. then
                        cT = 40;
                    else
                        cT = 11078;
                        continue;
                    end
                elseif cT == 11104 then
                    cT = if (cF*11+6.0)%20 == 18.0 then 209 else 33.;
                else
                    cT = 10969;
                    continue;
                end
            else
                cT = 17;
            end
        elseif cT < 11113 then
            if cT < 11110 then
                if cT < 11108 then
                    if cT < 11107 then
                        cT = 121;
                    elseif cT == 11107 then
                        cT = 12.;
                    else
                        cT = 11056;
                        continue;
                    end
                elseif cT < 11109. then
                    cT = 20;
                elseif cT == 11109. then
                    cG = (cG+45.0)%136;
                    cT = 99.;
                else
                    cT = 11073.;
                    continue;
                end
            elseif cT < 11112. then
                if cT < 11111 then
                    cT = if cG*4704723.0+12.0+3.0 >= cG*4704723.0+12.0+3.0+1 then 131 else 50;
                elseif cT == 11111 then
                    cF = (cF+1)%20;
                    cT = 107;
                else
                    cT = 10985;
                    continue;
                end
            else
                cT = 206;
            end
        elseif cT < 11116 then
            if cT < 11115. then
                if cT < 11114 then
                    if cT == 11113 then
                        cT = 215;
                    else
                        cT = 11007.;
                        continue;
                    end
                else
                    cp = d5[242]:GetService("VirtualUser");
                    cT = 59;
                end
            else
                cT = 169;
            end
        elseif cT < 11242 then
            if cT < 11117 then
                if cT == 11116 then
                    cE = loadstring(d5[242]:HttpGet(cl .. "Library.lua"))();
                    cT = 152;
                else
                    cT = 10945;
                    continue;
                end
            elseif cT == 11117 then
                local eh = d5;
                cP = (vector.create((cG*6.0+4)%11+1, (cG*6.0+11)%13+1, (cG*11+14)%17+1));
                cQ = (vector.create((cG*1+7)%11+1, (cG*3.0+12.0)%13+1, (cG*9.0+7)%17+1));
                cR = (vector.create((cG*3.0+6.0)%11+1, (cG*5+8)%13+1, (cG*11+6.0)%17+1));
                cS = (vector.create((cG*2+6.0)%5+1, (cG*1+4)%7+1, (cG*3.0+1)%9.0+1));
                cT = if vector.dot(vector.cross(cP, (vector.cross(cQ, cR))), cS) == vector.dot(cQ*vector.dot(cP, cR)-cR*vector.dot(cP, cQ), cS)+3.0 then 90. else 28;
            else
                cT = 11014;
                continue;
            end
        else
            break;
        end
    end
end
