import type { JobStats } from "@/db/schema";
import { lex, LexError, Token } from "./lexer";
import { parseTree, ParseError, Body } from "./tree";
import { format } from "./format";
import {
  cleanIndexing,
  decodeStrings,
  foldLiterals,
  normalizeNumbers,
  removeDeadLocals,
  resugarShortCircuit,
  tidyStructure,
} from "./passes/simple";
import { resolveConstantTable } from "./passes/constants";
import { unflattenControlFlow } from "./passes/unflatten";
import { renameVariables } from "./passes/rename";

export interface DeobfOptions {
  rename?: boolean;
  unflatten?: boolean;
  removeDeadCode?: boolean;
}

export interface DeobfResult {
  output: string;
  stats: JobStats;
  header: string | null;
}

export interface Detection {
  obfuscator: string | null;
  version: string | null;
  signals: string[];
}

export function detectObfuscator(src: string): Detection {
  const signals: string[] = [];
  let obfuscator: string | null = null;
  let version: string | null = null;
  const head = src.slice(0, 4000);
  const m = /generated by (luast)\s*v?([0-9.]+)?/i.exec(head);
  if (m) {
    obfuscator = "luast";
    version = m[2] ?? null;
    signals.push("luast watermark comment");
  }
  if (/luraph/i.test(head)) {
    obfuscator = obfuscator ?? "luraph";
    signals.push("luraph watermark");
  }
  if (/moonsec/i.test(head)) {
    obfuscator = obfuscator ?? "moonsec";
    signals.push("moonsec watermark");
  }
  if (/prometheus/i.test(head)) {
    obfuscator = obfuscator ?? "prometheus";
    signals.push("prometheus watermark");
  }
  if (/ironbrew|iron brew/i.test(head)) {
    obfuscator = obfuscator ?? "ironbrew";
    signals.push("ironbrew watermark");
  }
  if (/while true do \w+ = \d+\.? - \w+;/.test(src)) signals.push("state-encoded dispatcher (S = K - S)");
  if (/\w+\[\d+\.?\](?:, \w+\[\d+\.?\]){3,} = /.test(src)) signals.push("runtime constant-pool shuffling");
  if (/local \w+ = \w+; *\w+\[\d+\]/.test(src)) signals.push("constant-pool aliasing");
  if (/vector\.dot|vector\.angle|bit32\.(bxor|band|rrotate)/.test(src)) signals.push("opaque predicates (vector/bit32)");
  if (/= if .+ then \d+\.? else \d+\.?/.test(src)) signals.push("Luau if-expressions encoding state transitions");
  if (/\\\d{2,3}\\\d{2,3}\\\d{2,3}/.test(src)) signals.push("decimal-escaped strings");
  if (/\\x[0-9a-fA-F]{2}\\x[0-9a-fA-F]{2}/.test(src)) signals.push("hex-escaped strings");
  if (/string\.char\(\s*\d+\s*(,\s*\d+\s*){3,}\)/.test(src)) signals.push("string.char() constructed strings");
  if (/getfenv|setfenv|loadstring\(/.test(src)) signals.push("environment manipulation / loadstring");
  if (!obfuscator && signals.length >= 2) obfuscator = "generic (luast-like)";
  return { obfuscator, version, signals };
}

export function deobfuscate(source: string, opts: DeobfOptions = {}): DeobfResult {
  const started = Date.now();
  const options = { rename: true, unflatten: true, removeDeadCode: true, ...opts };
  const warnings: string[] = [];
  const detection = detectObfuscator(source);

  let tokens: Token[];
  try {
    tokens = lex(source);
  } catch (e) {
    throw new Error(`Lexer error: ${e instanceof LexError ? e.message : String(e)}`);
  }
  // Extract leading watermark comment
  let header: string | null = null;
  if (tokens[0]?.t === "cmt") {
    header = tokens[0].v;
    tokens = tokens.slice(1);
  }
  let tree: Body;
  try {
    tree = parseTree(tokens);
  } catch (e) {
    throw new Error(`Parse error: ${e instanceof ParseError ? e.message : String(e)}`);
  }

  const numbersNormalized = normalizeNumbers(tree);
  const stringsDecoded = decodeStrings(tree);

  const constants = resolveConstantTable(tree);
  warnings.push(...constants.warnings);

  let literalsFolded = foldLiterals(tree);
  literalsFolded += cleanIndexing(tree);

  let unflatten = { dispatchersFound: 0, dispatchersUnflattened: 0, statesRecovered: 0, arithmeticBranchesDecoded: 0, warnings: [] as string[] };
  if (options.unflatten) {
    unflatten = unflattenControlFlow(tree);
    warnings.push(...unflatten.warnings);
    literalsFolded += foldLiterals(tree);
  }
  literalsFolded += resugarShortCircuit(tree);
  literalsFolded += tidyStructure(tree);

  let deadLocalsRemoved = 0;
  if (options.removeDeadCode) deadLocalsRemoved = removeDeadLocals(tree);

  let variablesRenamed = 0;
  if (options.rename) variablesRenamed = renameVariables(tree);

  let output = format(tree);

  const confidence = computeConfidence({
    constants,
    unflatten,
  });

  const banner = [
    `-- Deobfuscated by Luast Deobfuscator Engine`,
    `-- Detected: ${detection.obfuscator ?? "unknown"}${detection.version ? " v" + detection.version : ""}`,
    `-- Constants resolved: ${constants.resolved}/${constants.tableSize || "n/a"} | dispatchers restructured: ${unflatten.dispatchersUnflattened}/${unflatten.dispatchersFound} (${unflatten.statesRecovered} states)`,
    `-- Note: identifiers and comments are destroyed by obfuscation; names below are reconstructed heuristically.`,
    warnings.length ? `-- Warnings: ${warnings.length} (see report)` : null,
  ]
    .filter(Boolean)
    .join("\n");
  output = banner + "\n\n" + output;

  const stats: JobStats = {
    obfuscator: detection.obfuscator,
    obfuscatorVersion: detection.version,
    constantsResolved: constants.resolved,
    constantTableSize: constants.tableSize,
    functionsHoisted: constants.hoisted,
    aliasesRemoved: constants.aliasesRemoved,
    swapsApplied: constants.swapsApplied,
    dispatchersFound: unflatten.dispatchersFound,
    dispatchersUnflattened: unflatten.dispatchersUnflattened,
    statesRecovered: unflatten.statesRecovered,
    arithmeticBranchesDecoded: unflatten.arithmeticBranchesDecoded,
    literalsFolded,
    deadLocalsRemoved,
    variablesRenamed,
    stringsDecoded,
    numbersNormalized,
    warnings: dedupe(warnings).slice(0, 25),
    confidence,
    durationMs: Date.now() - started,
  };
  return { output, stats, header };
}

function dedupe(list: string[]): string[] {
  const seen = new Set<string>();
  return list.filter((w) => (seen.has(w) ? false : (seen.add(w), true)));
}

function computeConfidence(input: {
  constants: { found: boolean; tableSize: number; resolved: number };
  unflatten: { dispatchersFound: number; dispatchersUnflattened: number; warnings: string[] };
}): number {
  let score = 0.35;
  if (input.constants.found) score += 0.3;
  if (input.unflatten.dispatchersFound > 0) {
    const fallbackCount = input.unflatten.warnings.filter((w) => w.includes("could not be fully structured")).length;
    const ratio = (input.unflatten.dispatchersUnflattened - fallbackCount) / input.unflatten.dispatchersFound;
    score += 0.35 * Math.max(0, ratio);
  } else {
    score += 0.2;
  }
  return Math.round(Math.min(1, score) * 100);
}
